// Extensions to AccessPointService beyond CRUD. The contents of this file are
// merged by proto-merge into the generated access_point_svc.g.proto.

// Import the interface service definition to reference InterfaceRef.
import "wifi/interface_svc.g.proto";

service AccessPointService {
  // Scan discovers nearby APs using the given interface and returns the list.
  rpc Scan(AccessPointScanRequest) returns (AccessPointScanResponse);
}

message AccessPointScanRequest {
  // The wireless interface to scan with. Must be specified since a node may have
  // multiple interfaces.
  InterfaceRef interface = 1;
}

message AccessPointScanResponse {
  // List of discovered APs.
  repeated AccessPoint items = 1;
}
