// Code generated by protoc-gen-orm-service. DO NOT EDIT.
// source: wifi/access_point.proto.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/access_point_svc.g.proto

package wifi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessPointAddRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ssid          *string                `protobuf:"bytes,2,opt,name=ssid"`
	xxx_hidden_Bssid         *string                `protobuf:"bytes,3,opt,name=bssid"`
	xxx_hidden_Signal        int32                  `protobuf:"varint,4,opt,name=signal"`
	xxx_hidden_Frequency     uint32                 `protobuf:"varint,5,opt,name=frequency"`
	xxx_hidden_KeyManagement []KeyManagement        `protobuf:"varint,6,rep,packed,name=key_management,json=keyManagement,enum=wifi.KeyManagement"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AccessPointAddRequest) Reset() {
	*x = AccessPointAddRequest{}
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPointAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPointAddRequest) ProtoMessage() {}

func (x *AccessPointAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessPointAddRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AccessPointAddRequest) GetSsid() string {
	if x != nil {
		if x.xxx_hidden_Ssid != nil {
			return *x.xxx_hidden_Ssid
		}
		return ""
	}
	return ""
}

func (x *AccessPointAddRequest) GetBssid() string {
	if x != nil {
		if x.xxx_hidden_Bssid != nil {
			return *x.xxx_hidden_Bssid
		}
		return ""
	}
	return ""
}

func (x *AccessPointAddRequest) GetSignal() int32 {
	if x != nil {
		return x.xxx_hidden_Signal
	}
	return 0
}

func (x *AccessPointAddRequest) GetFrequency() uint32 {
	if x != nil {
		return x.xxx_hidden_Frequency
	}
	return 0
}

func (x *AccessPointAddRequest) GetKeyManagement() []KeyManagement {
	if x != nil {
		return x.xxx_hidden_KeyManagement
	}
	return nil
}

func (x *AccessPointAddRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *AccessPointAddRequest) SetSsid(v string) {
	x.xxx_hidden_Ssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *AccessPointAddRequest) SetBssid(v string) {
	x.xxx_hidden_Bssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *AccessPointAddRequest) SetSignal(v int32) {
	x.xxx_hidden_Signal = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *AccessPointAddRequest) SetFrequency(v uint32) {
	x.xxx_hidden_Frequency = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *AccessPointAddRequest) SetKeyManagement(v []KeyManagement) {
	x.xxx_hidden_KeyManagement = v
}

func (x *AccessPointAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AccessPointAddRequest) HasSsid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AccessPointAddRequest) HasBssid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AccessPointAddRequest) HasSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AccessPointAddRequest) HasFrequency() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AccessPointAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *AccessPointAddRequest) ClearSsid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ssid = nil
}

func (x *AccessPointAddRequest) ClearBssid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Bssid = nil
}

func (x *AccessPointAddRequest) ClearSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Signal = 0
}

func (x *AccessPointAddRequest) ClearFrequency() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Frequency = 0
}

type AccessPointAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            *string
	Ssid          *string
	Bssid         *string
	Signal        *int32
	Frequency     *uint32
	KeyManagement []KeyManagement
}

func (b0 AccessPointAddRequest_builder) Build() *AccessPointAddRequest {
	m0 := &AccessPointAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Ssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Ssid = b.Ssid
	}
	if b.Bssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Bssid = b.Bssid
	}
	if b.Signal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Signal = *b.Signal
	}
	if b.Frequency != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Frequency = *b.Frequency
	}
	x.xxx_hidden_KeyManagement = b.KeyManagement
	return m0
}

type AccessPointRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isAccessPointRef_Key   `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccessPointRef) Reset() {
	*x = AccessPointRef{}
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPointRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPointRef) ProtoMessage() {}

func (x *AccessPointRef) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessPointRef) GetId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*accessPointRef_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *AccessPointRef) SetId(v string) {
	x.xxx_hidden_Key = &accessPointRef_Id{v}
}

func (x *AccessPointRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *AccessPointRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*accessPointRef_Id)
	return ok
}

func (x *AccessPointRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *AccessPointRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*accessPointRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

const AccessPointRef_Key_not_set_case case_AccessPointRef_Key = 0
const AccessPointRef_Id_case case_AccessPointRef_Key = 1

func (x *AccessPointRef) WhichKey() case_AccessPointRef_Key {
	if x == nil {
		return AccessPointRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *accessPointRef_Id:
		return AccessPointRef_Id_case
	default:
		return AccessPointRef_Key_not_set_case
	}
}

type AccessPointRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id *string
	// -- end of xxx_hidden_Key
}

func (b0 AccessPointRef_builder) Build() *AccessPointRef {
	m0 := &AccessPointRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &accessPointRef_Id{*b.Id}
	}
	return m0
}

type case_AccessPointRef_Key protoreflect.FieldNumber

func (x case_AccessPointRef_Key) String() string {
	md := file_wifi_access_point_svc_g_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAccessPointRef_Key interface {
	isAccessPointRef_Key()
}

type accessPointRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,oneof"`
}

func (*accessPointRef_Id) isAccessPointRef_Key() {}

type AccessPointSelect struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All           bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Ssid          bool                   `protobuf:"varint,2,opt,name=ssid"`
	xxx_hidden_Bssid         bool                   `protobuf:"varint,3,opt,name=bssid"`
	xxx_hidden_Signal        bool                   `protobuf:"varint,4,opt,name=signal"`
	xxx_hidden_Frequency     bool                   `protobuf:"varint,5,opt,name=frequency"`
	xxx_hidden_KeyManagement bool                   `protobuf:"varint,6,opt,name=key_management,json=keyManagement"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AccessPointSelect) Reset() {
	*x = AccessPointSelect{}
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPointSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPointSelect) ProtoMessage() {}

func (x *AccessPointSelect) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessPointSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *AccessPointSelect) GetSsid() bool {
	if x != nil {
		return x.xxx_hidden_Ssid
	}
	return false
}

func (x *AccessPointSelect) GetBssid() bool {
	if x != nil {
		return x.xxx_hidden_Bssid
	}
	return false
}

func (x *AccessPointSelect) GetSignal() bool {
	if x != nil {
		return x.xxx_hidden_Signal
	}
	return false
}

func (x *AccessPointSelect) GetFrequency() bool {
	if x != nil {
		return x.xxx_hidden_Frequency
	}
	return false
}

func (x *AccessPointSelect) GetKeyManagement() bool {
	if x != nil {
		return x.xxx_hidden_KeyManagement
	}
	return false
}

func (x *AccessPointSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *AccessPointSelect) SetSsid(v bool) {
	x.xxx_hidden_Ssid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *AccessPointSelect) SetBssid(v bool) {
	x.xxx_hidden_Bssid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *AccessPointSelect) SetSignal(v bool) {
	x.xxx_hidden_Signal = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *AccessPointSelect) SetFrequency(v bool) {
	x.xxx_hidden_Frequency = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *AccessPointSelect) SetKeyManagement(v bool) {
	x.xxx_hidden_KeyManagement = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *AccessPointSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AccessPointSelect) HasSsid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AccessPointSelect) HasBssid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AccessPointSelect) HasSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AccessPointSelect) HasFrequency() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AccessPointSelect) HasKeyManagement() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AccessPointSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *AccessPointSelect) ClearSsid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ssid = false
}

func (x *AccessPointSelect) ClearBssid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Bssid = false
}

func (x *AccessPointSelect) ClearSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Signal = false
}

func (x *AccessPointSelect) ClearFrequency() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Frequency = false
}

func (x *AccessPointSelect) ClearKeyManagement() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_KeyManagement = false
}

type AccessPointSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All           *bool
	Ssid          *bool
	Bssid         *bool
	Signal        *bool
	Frequency     *bool
	KeyManagement *bool
}

func (b0 AccessPointSelect_builder) Build() *AccessPointSelect {
	m0 := &AccessPointSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_All = *b.All
	}
	if b.Ssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Ssid = *b.Ssid
	}
	if b.Bssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Bssid = *b.Bssid
	}
	if b.Signal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Signal = *b.Signal
	}
	if b.Frequency != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Frequency = *b.Frequency
	}
	if b.KeyManagement != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_KeyManagement = *b.KeyManagement
	}
	return m0
}

type AccessPointGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *AccessPointRef        `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *AccessPointSelect     `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AccessPointGetRequest) Reset() {
	*x = AccessPointGetRequest{}
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPointGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPointGetRequest) ProtoMessage() {}

func (x *AccessPointGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessPointGetRequest) GetRef() *AccessPointRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AccessPointGetRequest) GetSelect() *AccessPointSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *AccessPointGetRequest) SetRef(v *AccessPointRef) {
	x.xxx_hidden_Ref = v
}

func (x *AccessPointGetRequest) SetSelect(v *AccessPointSelect) {
	x.xxx_hidden_Select = v
}

func (x *AccessPointGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AccessPointGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *AccessPointGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AccessPointGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type AccessPointGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *AccessPointRef
	Select *AccessPointSelect
}

func (b0 AccessPointGetRequest_builder) Build() *AccessPointGetRequest {
	m0 := &AccessPointGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type AccessPointPatchRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref           *AccessPointRef        `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Ssid          *string                `protobuf:"bytes,3,opt,name=ssid"`
	xxx_hidden_SsidNull      bool                   `protobuf:"varint,4,opt,name=ssid_null,json=ssidNull"`
	xxx_hidden_Bssid         *string                `protobuf:"bytes,5,opt,name=bssid"`
	xxx_hidden_BssidNull     bool                   `protobuf:"varint,6,opt,name=bssid_null,json=bssidNull"`
	xxx_hidden_Signal        int32                  `protobuf:"varint,7,opt,name=signal"`
	xxx_hidden_SignalNull    bool                   `protobuf:"varint,8,opt,name=signal_null,json=signalNull"`
	xxx_hidden_Frequency     uint32                 `protobuf:"varint,9,opt,name=frequency"`
	xxx_hidden_FrequencyNull bool                   `protobuf:"varint,10,opt,name=frequency_null,json=frequencyNull"`
	xxx_hidden_KeyManagement []KeyManagement        `protobuf:"varint,11,rep,packed,name=key_management,json=keyManagement,enum=wifi.KeyManagement"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AccessPointPatchRequest) Reset() {
	*x = AccessPointPatchRequest{}
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPointPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPointPatchRequest) ProtoMessage() {}

func (x *AccessPointPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessPointPatchRequest) GetRef() *AccessPointRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AccessPointPatchRequest) GetSsid() string {
	if x != nil {
		if x.xxx_hidden_Ssid != nil {
			return *x.xxx_hidden_Ssid
		}
		return ""
	}
	return ""
}

func (x *AccessPointPatchRequest) GetSsidNull() bool {
	if x != nil {
		return x.xxx_hidden_SsidNull
	}
	return false
}

func (x *AccessPointPatchRequest) GetBssid() string {
	if x != nil {
		if x.xxx_hidden_Bssid != nil {
			return *x.xxx_hidden_Bssid
		}
		return ""
	}
	return ""
}

func (x *AccessPointPatchRequest) GetBssidNull() bool {
	if x != nil {
		return x.xxx_hidden_BssidNull
	}
	return false
}

func (x *AccessPointPatchRequest) GetSignal() int32 {
	if x != nil {
		return x.xxx_hidden_Signal
	}
	return 0
}

func (x *AccessPointPatchRequest) GetSignalNull() bool {
	if x != nil {
		return x.xxx_hidden_SignalNull
	}
	return false
}

func (x *AccessPointPatchRequest) GetFrequency() uint32 {
	if x != nil {
		return x.xxx_hidden_Frequency
	}
	return 0
}

func (x *AccessPointPatchRequest) GetFrequencyNull() bool {
	if x != nil {
		return x.xxx_hidden_FrequencyNull
	}
	return false
}

func (x *AccessPointPatchRequest) GetKeyManagement() []KeyManagement {
	if x != nil {
		return x.xxx_hidden_KeyManagement
	}
	return nil
}

func (x *AccessPointPatchRequest) SetRef(v *AccessPointRef) {
	x.xxx_hidden_Ref = v
}

func (x *AccessPointPatchRequest) SetSsid(v string) {
	x.xxx_hidden_Ssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *AccessPointPatchRequest) SetSsidNull(v bool) {
	x.xxx_hidden_SsidNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *AccessPointPatchRequest) SetBssid(v string) {
	x.xxx_hidden_Bssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *AccessPointPatchRequest) SetBssidNull(v bool) {
	x.xxx_hidden_BssidNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *AccessPointPatchRequest) SetSignal(v int32) {
	x.xxx_hidden_Signal = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *AccessPointPatchRequest) SetSignalNull(v bool) {
	x.xxx_hidden_SignalNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *AccessPointPatchRequest) SetFrequency(v uint32) {
	x.xxx_hidden_Frequency = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *AccessPointPatchRequest) SetFrequencyNull(v bool) {
	x.xxx_hidden_FrequencyNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 10)
}

func (x *AccessPointPatchRequest) SetKeyManagement(v []KeyManagement) {
	x.xxx_hidden_KeyManagement = v
}

func (x *AccessPointPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AccessPointPatchRequest) HasSsid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AccessPointPatchRequest) HasSsidNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AccessPointPatchRequest) HasBssid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AccessPointPatchRequest) HasBssidNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AccessPointPatchRequest) HasSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AccessPointPatchRequest) HasSignalNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *AccessPointPatchRequest) HasFrequency() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *AccessPointPatchRequest) HasFrequencyNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *AccessPointPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AccessPointPatchRequest) ClearSsid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ssid = nil
}

func (x *AccessPointPatchRequest) ClearSsidNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SsidNull = false
}

func (x *AccessPointPatchRequest) ClearBssid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Bssid = nil
}

func (x *AccessPointPatchRequest) ClearBssidNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_BssidNull = false
}

func (x *AccessPointPatchRequest) ClearSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Signal = 0
}

func (x *AccessPointPatchRequest) ClearSignalNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_SignalNull = false
}

func (x *AccessPointPatchRequest) ClearFrequency() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Frequency = 0
}

func (x *AccessPointPatchRequest) ClearFrequencyNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_FrequencyNull = false
}

type AccessPointPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref           *AccessPointRef
	Ssid          *string
	SsidNull      *bool
	Bssid         *string
	BssidNull     *bool
	Signal        *int32
	SignalNull    *bool
	Frequency     *uint32
	FrequencyNull *bool
	KeyManagement []KeyManagement
}

func (b0 AccessPointPatchRequest_builder) Build() *AccessPointPatchRequest {
	m0 := &AccessPointPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Ssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_Ssid = b.Ssid
	}
	if b.SsidNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_SsidNull = *b.SsidNull
	}
	if b.Bssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_Bssid = b.Bssid
	}
	if b.BssidNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_BssidNull = *b.BssidNull
	}
	if b.Signal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_Signal = *b.Signal
	}
	if b.SignalNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_SignalNull = *b.SignalNull
	}
	if b.Frequency != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_Frequency = *b.Frequency
	}
	if b.FrequencyNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 10)
		x.xxx_hidden_FrequencyNull = *b.FrequencyNull
	}
	x.xxx_hidden_KeyManagement = b.KeyManagement
	return m0
}

type AccessPointScanRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Interface *InterfaceRef          `protobuf:"bytes,1,opt,name=interface"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AccessPointScanRequest) Reset() {
	*x = AccessPointScanRequest{}
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPointScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPointScanRequest) ProtoMessage() {}

func (x *AccessPointScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessPointScanRequest) GetInterface() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Interface
	}
	return nil
}

func (x *AccessPointScanRequest) SetInterface(v *InterfaceRef) {
	x.xxx_hidden_Interface = v
}

func (x *AccessPointScanRequest) HasInterface() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Interface != nil
}

func (x *AccessPointScanRequest) ClearInterface() {
	x.xxx_hidden_Interface = nil
}

type AccessPointScanRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 스캔에 사용할 무선 인터페이스. 노드에 인터페이스가 여러 개일 수 있으므로
	// 반드시 지정한다.
	Interface *InterfaceRef
}

func (b0 AccessPointScanRequest_builder) Build() *AccessPointScanRequest {
	m0 := &AccessPointScanRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Interface = b.Interface
	return m0
}

type AccessPointScanResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*AccessPoint        `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccessPointScanResponse) Reset() {
	*x = AccessPointScanResponse{}
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPointScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPointScanResponse) ProtoMessage() {}

func (x *AccessPointScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_access_point_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessPointScanResponse) GetItems() []*AccessPoint {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *AccessPointScanResponse) SetItems(v []*AccessPoint) {
	x.xxx_hidden_Items = &v
}

type AccessPointScanResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 발견된 AP 목록.
	Items []*AccessPoint
}

func (b0 AccessPointScanResponse_builder) Build() *AccessPointScanResponse {
	m0 := &AccessPointScanResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

var File_wifi_access_point_svc_g_proto protoreflect.FileDescriptor

const file_wifi_access_point_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x1dwifi/access_point_svc.g.proto\x12\x04wifi\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17wifi/access_point.proto\x1a\x1awifi/interface_svc.g.proto\"\xc3\x01\n" +
	"\x15AccessPointAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04ssid\x18\x02 \x01(\tR\x04ssid\x12\x14\n" +
	"\x05bssid\x18\x03 \x01(\tR\x05bssid\x12\x16\n" +
	"\x06signal\x18\x04 \x01(\x05R\x06signal\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\rR\tfrequency\x12:\n" +
	"\x0ekey_management\x18\x06 \x03(\x0e2\x13.wifi.KeyManagementR\rkeyManagement\")\n" +
	"\x0eAccessPointRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02idB\x05\n" +
	"\x03key\"\xac\x01\n" +
	"\x11AccessPointSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x12\n" +
	"\x04ssid\x18\x02 \x01(\bR\x04ssid\x12\x14\n" +
	"\x05bssid\x18\x03 \x01(\bR\x05bssid\x12\x16\n" +
	"\x06signal\x18\x04 \x01(\bR\x06signal\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\bR\tfrequency\x12%\n" +
	"\x0ekey_management\x18\x06 \x01(\bR\rkeyManagement\"p\n" +
	"\x15AccessPointGetRequest\x12&\n" +
	"\x03ref\x18\x01 \x01(\v2\x14.wifi.AccessPointRefR\x03ref\x12/\n" +
	"\x06select\x18\x02 \x01(\v2\x17.wifi.AccessPointSelectR\x06select\"\xe1\x02\n" +
	"\x17AccessPointPatchRequest\x12&\n" +
	"\x03ref\x18\x01 \x01(\v2\x14.wifi.AccessPointRefR\x03ref\x12\x12\n" +
	"\x04ssid\x18\x03 \x01(\tR\x04ssid\x12\x1b\n" +
	"\tssid_null\x18\x04 \x01(\bR\bssidNull\x12\x14\n" +
	"\x05bssid\x18\x05 \x01(\tR\x05bssid\x12\x1d\n" +
	"\n" +
	"bssid_null\x18\x06 \x01(\bR\tbssidNull\x12\x16\n" +
	"\x06signal\x18\a \x01(\x05R\x06signal\x12\x1f\n" +
	"\vsignal_null\x18\b \x01(\bR\n" +
	"signalNull\x12\x1c\n" +
	"\tfrequency\x18\t \x01(\rR\tfrequency\x12%\n" +
	"\x0efrequency_null\x18\n" +
	" \x01(\bR\rfrequencyNull\x12:\n" +
	"\x0ekey_management\x18\v \x03(\x0e2\x13.wifi.KeyManagementR\rkeyManagement\"J\n" +
	"\x16AccessPointScanRequest\x120\n" +
	"\tinterface\x18\x01 \x01(\v2\x12.wifi.InterfaceRefR\tinterface\"B\n" +
	"\x17AccessPointScanResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.wifi.AccessPointR\x05items2\xb9\x02\n" +
	"\x12AccessPointService\x125\n" +
	"\x03Add\x12\x1b.wifi.AccessPointAddRequest\x1a\x11.wifi.AccessPoint\x125\n" +
	"\x03Get\x12\x1b.wifi.AccessPointGetRequest\x1a\x11.wifi.AccessPoint\x129\n" +
	"\x05Patch\x12\x1d.wifi.AccessPointPatchRequest\x1a\x11.wifi.AccessPoint\x125\n" +
	"\x05Erase\x12\x14.wifi.AccessPointRef\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x04Scan\x12\x1c.wifi.AccessPointScanRequest\x1a\x1d.wifi.AccessPointScanResponseB'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_access_point_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wifi_access_point_svc_g_proto_goTypes = []any{
	(*AccessPointAddRequest)(nil),   // 0: wifi.AccessPointAddRequest
	(*AccessPointRef)(nil),          // 1: wifi.AccessPointRef
	(*AccessPointSelect)(nil),       // 2: wifi.AccessPointSelect
	(*AccessPointGetRequest)(nil),   // 3: wifi.AccessPointGetRequest
	(*AccessPointPatchRequest)(nil), // 4: wifi.AccessPointPatchRequest
	(*AccessPointScanRequest)(nil),  // 5: wifi.AccessPointScanRequest
	(*AccessPointScanResponse)(nil), // 6: wifi.AccessPointScanResponse
	(KeyManagement)(0),              // 7: wifi.KeyManagement
	(*InterfaceRef)(nil),            // 8: wifi.InterfaceRef
	(*AccessPoint)(nil),             // 9: wifi.AccessPoint
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
}
var file_wifi_access_point_svc_g_proto_depIdxs = []int32{
	7,  // 0: wifi.AccessPointAddRequest.key_management:type_name -> wifi.KeyManagement
	1,  // 1: wifi.AccessPointGetRequest.ref:type_name -> wifi.AccessPointRef
	2,  // 2: wifi.AccessPointGetRequest.select:type_name -> wifi.AccessPointSelect
	1,  // 3: wifi.AccessPointPatchRequest.ref:type_name -> wifi.AccessPointRef
	7,  // 4: wifi.AccessPointPatchRequest.key_management:type_name -> wifi.KeyManagement
	8,  // 5: wifi.AccessPointScanRequest.interface:type_name -> wifi.InterfaceRef
	9,  // 6: wifi.AccessPointScanResponse.items:type_name -> wifi.AccessPoint
	0,  // 7: wifi.AccessPointService.Add:input_type -> wifi.AccessPointAddRequest
	3,  // 8: wifi.AccessPointService.Get:input_type -> wifi.AccessPointGetRequest
	4,  // 9: wifi.AccessPointService.Patch:input_type -> wifi.AccessPointPatchRequest
	1,  // 10: wifi.AccessPointService.Erase:input_type -> wifi.AccessPointRef
	5,  // 11: wifi.AccessPointService.Scan:input_type -> wifi.AccessPointScanRequest
	9,  // 12: wifi.AccessPointService.Add:output_type -> wifi.AccessPoint
	9,  // 13: wifi.AccessPointService.Get:output_type -> wifi.AccessPoint
	9,  // 14: wifi.AccessPointService.Patch:output_type -> wifi.AccessPoint
	10, // 15: wifi.AccessPointService.Erase:output_type -> google.protobuf.Empty
	6,  // 16: wifi.AccessPointService.Scan:output_type -> wifi.AccessPointScanResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_wifi_access_point_svc_g_proto_init() }
func file_wifi_access_point_svc_g_proto_init() {
	if File_wifi_access_point_svc_g_proto != nil {
		return
	}
	file_wifi_access_point_proto_init()
	file_wifi_interface_svc_g_proto_init()
	file_wifi_access_point_svc_g_proto_msgTypes[1].OneofWrappers = []any{
		(*accessPointRef_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_access_point_svc_g_proto_rawDesc), len(file_wifi_access_point_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wifi_access_point_svc_g_proto_goTypes,
		DependencyIndexes: file_wifi_access_point_svc_g_proto_depIdxs,
		MessageInfos:      file_wifi_access_point_svc_g_proto_msgTypes,
	}.Build()
	File_wifi_access_point_svc_g_proto = out.File
	file_wifi_access_point_svc_g_proto_goTypes = nil
	file_wifi_access_point_svc_g_proto_depIdxs = nil
}
