// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/access_point.proto

package wifi

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyManagement identifies the authentication/key-management protocol an AP uses.
//
// In scan results (AccessPoint) it indicates "the methods the AP supports", and
// paired with a Profile's Security it is used to decide which credentials must
// be used.
type KeyManagement int32

const (
	KeyManagement_KEY_MANAGEMENT_UNSPECIFIED KeyManagement = 0
	// Open network. No authentication.
	KeyManagement_KEY_MANAGEMENT_NONE KeyManagement = 1
	// WPA/WPA2 personal. Based on a pre-shared key (password).
	KeyManagement_KEY_MANAGEMENT_WPA_PSK KeyManagement = 2
	// WPA3 personal (SAE). Also password based.
	KeyManagement_KEY_MANAGEMENT_SAE KeyManagement = 3
	// WPA/WPA2/WPA3 enterprise (802.1X/EAP). Not implemented yet.
	KeyManagement_KEY_MANAGEMENT_WPA_EAP KeyManagement = 4
	// Enhanced Open (OWE). Encrypts without a password. Not implemented yet.
	KeyManagement_KEY_MANAGEMENT_OWE KeyManagement = 5
)

// Enum value maps for KeyManagement.
var (
	KeyManagement_name = map[int32]string{
		0: "KEY_MANAGEMENT_UNSPECIFIED",
		1: "KEY_MANAGEMENT_NONE",
		2: "KEY_MANAGEMENT_WPA_PSK",
		3: "KEY_MANAGEMENT_SAE",
		4: "KEY_MANAGEMENT_WPA_EAP",
		5: "KEY_MANAGEMENT_OWE",
	}
	KeyManagement_value = map[string]int32{
		"KEY_MANAGEMENT_UNSPECIFIED": 0,
		"KEY_MANAGEMENT_NONE":        1,
		"KEY_MANAGEMENT_WPA_PSK":     2,
		"KEY_MANAGEMENT_SAE":         3,
		"KEY_MANAGEMENT_WPA_EAP":     4,
		"KEY_MANAGEMENT_OWE":         5,
	}
)

func (x KeyManagement) Enum() *KeyManagement {
	p := new(KeyManagement)
	*p = x
	return p
}

func (x KeyManagement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyManagement) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_access_point_proto_enumTypes[0].Descriptor()
}

func (KeyManagement) Type() protoreflect.EnumType {
	return &file_wifi_access_point_proto_enumTypes[0]
}

func (x KeyManagement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// AccessPoint represents a wireless network (BSS) discovered by a scan.
//
// Scan results are *discovered* through the radio environment rather than
// created by a client, so Add/Patch/Erase do not make semantic sense. However,
// for the convenience of testing (mocks, etc.) all CRUD operations are defined,
// and the real service implementation returns unimplemented for them. The scan
// itself is added by AccessPointService.Scan (access_point_svc.ext.proto).
type AccessPoint struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ssid          *string                `protobuf:"bytes,2,opt,name=ssid"`
	xxx_hidden_Bssid         *string                `protobuf:"bytes,3,opt,name=bssid"`
	xxx_hidden_Signal        int32                  `protobuf:"varint,4,opt,name=signal"`
	xxx_hidden_Frequency     uint32                 `protobuf:"varint,5,opt,name=frequency"`
	xxx_hidden_KeyManagement []KeyManagement        `protobuf:"varint,6,rep,packed,name=key_management,json=keyManagement,enum=wifi.KeyManagement"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AccessPoint) Reset() {
	*x = AccessPoint{}
	mi := &file_wifi_access_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPoint) ProtoMessage() {}

func (x *AccessPoint) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_access_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessPoint) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AccessPoint) GetSsid() string {
	if x != nil {
		if x.xxx_hidden_Ssid != nil {
			return *x.xxx_hidden_Ssid
		}
		return ""
	}
	return ""
}

func (x *AccessPoint) GetBssid() string {
	if x != nil {
		if x.xxx_hidden_Bssid != nil {
			return *x.xxx_hidden_Bssid
		}
		return ""
	}
	return ""
}

func (x *AccessPoint) GetSignal() int32 {
	if x != nil {
		return x.xxx_hidden_Signal
	}
	return 0
}

func (x *AccessPoint) GetFrequency() uint32 {
	if x != nil {
		return x.xxx_hidden_Frequency
	}
	return 0
}

func (x *AccessPoint) GetKeyManagement() []KeyManagement {
	if x != nil {
		return x.xxx_hidden_KeyManagement
	}
	return nil
}

func (x *AccessPoint) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *AccessPoint) SetSsid(v string) {
	x.xxx_hidden_Ssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *AccessPoint) SetBssid(v string) {
	x.xxx_hidden_Bssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *AccessPoint) SetSignal(v int32) {
	x.xxx_hidden_Signal = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *AccessPoint) SetFrequency(v uint32) {
	x.xxx_hidden_Frequency = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *AccessPoint) SetKeyManagement(v []KeyManagement) {
	x.xxx_hidden_KeyManagement = v
}

func (x *AccessPoint) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AccessPoint) HasSsid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AccessPoint) HasBssid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AccessPoint) HasSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AccessPoint) HasFrequency() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AccessPoint) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *AccessPoint) ClearSsid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ssid = nil
}

func (x *AccessPoint) ClearBssid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Bssid = nil
}

func (x *AccessPoint) ClearSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Signal = 0
}

func (x *AccessPoint) ClearFrequency() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Frequency = 0
}

type AccessPoint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Stable identifier of the discovered AP. Implementations may use the BSSID
	// directly.
	Id *string
	// Network name (SSID). May be empty for hidden networks.
	Ssid *string
	// Hardware address (BSSID) of the AP.
	Bssid *string
	// Signal quality (0-100). Higher is stronger (same scale as NetworkManager Strength).
	Signal *int32
	// Channel frequency (MHz). e.g. 2412 (2.4GHz), 5180 (5GHz).
	Frequency *uint32
	// The authentication/key-management methods this AP advertises.
	// A client looks at this list to pick a Profile with a matching Security.
	KeyManagement []KeyManagement
}

func (b0 AccessPoint_builder) Build() *AccessPoint {
	m0 := &AccessPoint{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Ssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Ssid = b.Ssid
	}
	if b.Bssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Bssid = b.Bssid
	}
	if b.Signal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Signal = *b.Signal
	}
	if b.Frequency != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Frequency = *b.Frequency
	}
	x.xxx_hidden_KeyManagement = b.KeyManagement
	return m0
}

var File_wifi_access_point_proto protoreflect.FileDescriptor

const file_wifi_access_point_proto_rawDesc = "" +
	"\n" +
	"\x17wifi/access_point.proto\x12\x04wifi\x1a\torm.proto\"\xf2\x01\n" +
	"\vAccessPoint\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xea\x82\x16\x05(\x01\x82\x01\x00R\x02id\x12\x1b\n" +
	"\x04ssid\x18\x02 \x01(\tB\a\xea\x82\x16\x03\x82\x01\x00R\x04ssid\x12\x1d\n" +
	"\x05bssid\x18\x03 \x01(\tB\a\xea\x82\x16\x03\x82\x01\x00R\x05bssid\x12\x1f\n" +
	"\x06signal\x18\x04 \x01(\x05B\a\xea\x82\x16\x03\x82\x01\x00R\x06signal\x12%\n" +
	"\tfrequency\x18\x05 \x01(\rB\a\xea\x82\x16\x03\x82\x01\x00R\tfrequency\x12:\n" +
	"\x0ekey_management\x18\x06 \x03(\x0e2\x13.wifi.KeyManagementR\rkeyManagement:\b\xca\xfc\x15\x04\x12\x02\x10\x01*\xb0\x01\n" +
	"\rKeyManagement\x12\x1e\n" +
	"\x1aKEY_MANAGEMENT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13KEY_MANAGEMENT_NONE\x10\x01\x12\x1a\n" +
	"\x16KEY_MANAGEMENT_WPA_PSK\x10\x02\x12\x16\n" +
	"\x12KEY_MANAGEMENT_SAE\x10\x03\x12\x1a\n" +
	"\x16KEY_MANAGEMENT_WPA_EAP\x10\x04\x12\x16\n" +
	"\x12KEY_MANAGEMENT_OWE\x10\x05B'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_access_point_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wifi_access_point_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wifi_access_point_proto_goTypes = []any{
	(KeyManagement)(0),  // 0: wifi.KeyManagement
	(*AccessPoint)(nil), // 1: wifi.AccessPoint
}
var file_wifi_access_point_proto_depIdxs = []int32{
	0, // 0: wifi.AccessPoint.key_management:type_name -> wifi.KeyManagement
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wifi_access_point_proto_init() }
func file_wifi_access_point_proto_init() {
	if File_wifi_access_point_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_access_point_proto_rawDesc), len(file_wifi_access_point_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_access_point_proto_goTypes,
		DependencyIndexes: file_wifi_access_point_proto_depIdxs,
		EnumInfos:         file_wifi_access_point_proto_enumTypes,
		MessageInfos:      file_wifi_access_point_proto_msgTypes,
	}.Build()
	File_wifi_access_point_proto = out.File
	file_wifi_access_point_proto_goTypes = nil
	file_wifi_access_point_proto_depIdxs = nil
}
