// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/access_point.proto

package wifi

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyManagement는 AP가 사용하는 인증/키 관리 프로토콜을 식별한다.
//
// 스캔 결과(AccessPoint)에서는 "AP가 지원하는 방식"을 나타내고,
// 프로파일(Profile)의 Security와 짝을 이루어 어떤 자격 증명을 써야 하는지를
// 결정하는 데 쓰인다.
type KeyManagement int32

const (
	KeyManagement_KEY_MANAGEMENT_UNSPECIFIED KeyManagement = 0
	// 개방형 네트워크. 인증이 없다.
	KeyManagement_KEY_MANAGEMENT_NONE KeyManagement = 1
	// WPA/WPA2 personal. 사전 공유 키(비밀번호) 기반.
	KeyManagement_KEY_MANAGEMENT_WPA_PSK KeyManagement = 2
	// WPA3 personal (SAE). 마찬가지로 비밀번호 기반.
	KeyManagement_KEY_MANAGEMENT_SAE KeyManagement = 3
	// WPA/WPA2/WPA3 enterprise (802.1X/EAP). 아직 구현되지 않음.
	KeyManagement_KEY_MANAGEMENT_WPA_EAP KeyManagement = 4
	// Enhanced Open (OWE). 비밀번호 없이 암호화한다. 아직 구현되지 않음.
	KeyManagement_KEY_MANAGEMENT_OWE KeyManagement = 5
)

// Enum value maps for KeyManagement.
var (
	KeyManagement_name = map[int32]string{
		0: "KEY_MANAGEMENT_UNSPECIFIED",
		1: "KEY_MANAGEMENT_NONE",
		2: "KEY_MANAGEMENT_WPA_PSK",
		3: "KEY_MANAGEMENT_SAE",
		4: "KEY_MANAGEMENT_WPA_EAP",
		5: "KEY_MANAGEMENT_OWE",
	}
	KeyManagement_value = map[string]int32{
		"KEY_MANAGEMENT_UNSPECIFIED": 0,
		"KEY_MANAGEMENT_NONE":        1,
		"KEY_MANAGEMENT_WPA_PSK":     2,
		"KEY_MANAGEMENT_SAE":         3,
		"KEY_MANAGEMENT_WPA_EAP":     4,
		"KEY_MANAGEMENT_OWE":         5,
	}
)

func (x KeyManagement) Enum() *KeyManagement {
	p := new(KeyManagement)
	*p = x
	return p
}

func (x KeyManagement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyManagement) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_access_point_proto_enumTypes[0].Descriptor()
}

func (KeyManagement) Type() protoreflect.EnumType {
	return &file_wifi_access_point_proto_enumTypes[0]
}

func (x KeyManagement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// AccessPoint는 스캔으로 발견된 무선 네트워크(BSS)를 나타낸다.
//
// 스캔 결과는 라디오 환경에 의해 *발견*되는 것이지 클라이언트가 만드는
// 것이 아니므로 Add/Patch/Erase는 의미상 맞지 않는다. 다만 테스트(mock 등)의
// 편의를 위해 CRUD를 모두 정의해 두고, 실제 서비스 구현은 이들에 대해
// unimplemented를 반환한다. 스캔 자체는 AccessPointService.Scan
// (access_point_svc.ext.proto)에서 추가한다.
type AccessPoint struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ssid          *string                `protobuf:"bytes,2,opt,name=ssid"`
	xxx_hidden_Bssid         *string                `protobuf:"bytes,3,opt,name=bssid"`
	xxx_hidden_Signal        int32                  `protobuf:"varint,4,opt,name=signal"`
	xxx_hidden_Frequency     uint32                 `protobuf:"varint,5,opt,name=frequency"`
	xxx_hidden_KeyManagement []KeyManagement        `protobuf:"varint,6,rep,packed,name=key_management,json=keyManagement,enum=wifi.KeyManagement"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AccessPoint) Reset() {
	*x = AccessPoint{}
	mi := &file_wifi_access_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPoint) ProtoMessage() {}

func (x *AccessPoint) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_access_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessPoint) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AccessPoint) GetSsid() string {
	if x != nil {
		if x.xxx_hidden_Ssid != nil {
			return *x.xxx_hidden_Ssid
		}
		return ""
	}
	return ""
}

func (x *AccessPoint) GetBssid() string {
	if x != nil {
		if x.xxx_hidden_Bssid != nil {
			return *x.xxx_hidden_Bssid
		}
		return ""
	}
	return ""
}

func (x *AccessPoint) GetSignal() int32 {
	if x != nil {
		return x.xxx_hidden_Signal
	}
	return 0
}

func (x *AccessPoint) GetFrequency() uint32 {
	if x != nil {
		return x.xxx_hidden_Frequency
	}
	return 0
}

func (x *AccessPoint) GetKeyManagement() []KeyManagement {
	if x != nil {
		return x.xxx_hidden_KeyManagement
	}
	return nil
}

func (x *AccessPoint) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *AccessPoint) SetSsid(v string) {
	x.xxx_hidden_Ssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *AccessPoint) SetBssid(v string) {
	x.xxx_hidden_Bssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *AccessPoint) SetSignal(v int32) {
	x.xxx_hidden_Signal = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *AccessPoint) SetFrequency(v uint32) {
	x.xxx_hidden_Frequency = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *AccessPoint) SetKeyManagement(v []KeyManagement) {
	x.xxx_hidden_KeyManagement = v
}

func (x *AccessPoint) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AccessPoint) HasSsid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AccessPoint) HasBssid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AccessPoint) HasSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AccessPoint) HasFrequency() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AccessPoint) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *AccessPoint) ClearSsid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ssid = nil
}

func (x *AccessPoint) ClearBssid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Bssid = nil
}

func (x *AccessPoint) ClearSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Signal = 0
}

func (x *AccessPoint) ClearFrequency() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Frequency = 0
}

type AccessPoint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 발견된 AP의 안정적인 식별자. 구현은 BSSID를 그대로 쓸 수 있다.
	Id *string
	// 네트워크 이름(SSID). 히든 네트워크의 경우 비어 있을 수 있다.
	Ssid *string
	// AP의 하드웨어 주소(BSSID).
	Bssid *string
	// 신호 품질(0-100). 클수록 강하다(NetworkManager Strength와 동일 척도).
	Signal *int32
	// 채널 주파수(MHz). 예: 2412(2.4GHz), 5180(5GHz).
	Frequency *uint32
	// 이 AP가 광고하는 인증/키 관리 방식들.
	// 클라이언트는 이 목록을 보고 알맞은 Security를 가진 Profile을 고른다.
	KeyManagement []KeyManagement
}

func (b0 AccessPoint_builder) Build() *AccessPoint {
	m0 := &AccessPoint{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Ssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Ssid = b.Ssid
	}
	if b.Bssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Bssid = b.Bssid
	}
	if b.Signal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Signal = *b.Signal
	}
	if b.Frequency != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Frequency = *b.Frequency
	}
	x.xxx_hidden_KeyManagement = b.KeyManagement
	return m0
}

var File_wifi_access_point_proto protoreflect.FileDescriptor

const file_wifi_access_point_proto_rawDesc = "" +
	"\n" +
	"\x17wifi/access_point.proto\x12\x04wifi\x1a\torm.proto\"\xf2\x01\n" +
	"\vAccessPoint\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xea\x82\x16\x05(\x01\x82\x01\x00R\x02id\x12\x1b\n" +
	"\x04ssid\x18\x02 \x01(\tB\a\xea\x82\x16\x03\x82\x01\x00R\x04ssid\x12\x1d\n" +
	"\x05bssid\x18\x03 \x01(\tB\a\xea\x82\x16\x03\x82\x01\x00R\x05bssid\x12\x1f\n" +
	"\x06signal\x18\x04 \x01(\x05B\a\xea\x82\x16\x03\x82\x01\x00R\x06signal\x12%\n" +
	"\tfrequency\x18\x05 \x01(\rB\a\xea\x82\x16\x03\x82\x01\x00R\tfrequency\x12:\n" +
	"\x0ekey_management\x18\x06 \x03(\x0e2\x13.wifi.KeyManagementR\rkeyManagement:\b\xca\xfc\x15\x04\x12\x02\x10\x01*\xb0\x01\n" +
	"\rKeyManagement\x12\x1e\n" +
	"\x1aKEY_MANAGEMENT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13KEY_MANAGEMENT_NONE\x10\x01\x12\x1a\n" +
	"\x16KEY_MANAGEMENT_WPA_PSK\x10\x02\x12\x16\n" +
	"\x12KEY_MANAGEMENT_SAE\x10\x03\x12\x1a\n" +
	"\x16KEY_MANAGEMENT_WPA_EAP\x10\x04\x12\x16\n" +
	"\x12KEY_MANAGEMENT_OWE\x10\x05B'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_access_point_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wifi_access_point_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wifi_access_point_proto_goTypes = []any{
	(KeyManagement)(0),  // 0: wifi.KeyManagement
	(*AccessPoint)(nil), // 1: wifi.AccessPoint
}
var file_wifi_access_point_proto_depIdxs = []int32{
	0, // 0: wifi.AccessPoint.key_management:type_name -> wifi.KeyManagement
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wifi_access_point_proto_init() }
func file_wifi_access_point_proto_init() {
	if File_wifi_access_point_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_access_point_proto_rawDesc), len(file_wifi_access_point_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_access_point_proto_goTypes,
		DependencyIndexes: file_wifi_access_point_proto_depIdxs,
		EnumInfos:         file_wifi_access_point_proto_enumTypes,
		MessageInfos:      file_wifi_access_point_proto_msgTypes,
	}.Build()
	File_wifi_access_point_proto = out.File
	file_wifi_access_point_proto_goTypes = nil
	file_wifi_access_point_proto_depIdxs = nil
}
