// Code generated by protoc-gen-orm-service. DO NOT EDIT.
// source: wifi/access_point.proto.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: wifi/access_point_svc.g.proto

package wifi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessPointService_Add_FullMethodName   = "/wifi.AccessPointService/Add"
	AccessPointService_Get_FullMethodName   = "/wifi.AccessPointService/Get"
	AccessPointService_Patch_FullMethodName = "/wifi.AccessPointService/Patch"
	AccessPointService_Erase_FullMethodName = "/wifi.AccessPointService/Erase"
	AccessPointService_Scan_FullMethodName  = "/wifi.AccessPointService/Scan"
)

// AccessPointServiceClient is the client API for AccessPointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessPointServiceClient interface {
	// Add creates a new AccessPoint
	Add(ctx context.Context, in *AccessPointAddRequest, opts ...grpc.CallOption) (*AccessPoint, error)
	// Get retrieves a AccessPoint
	Get(ctx context.Context, in *AccessPointGetRequest, opts ...grpc.CallOption) (*AccessPoint, error)
	// Patch updates an existing AccessPoint
	Patch(ctx context.Context, in *AccessPointPatchRequest, opts ...grpc.CallOption) (*AccessPoint, error)
	// Erase deletes a AccessPoint
	Erase(ctx context.Context, in *AccessPointRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Scan은 주어진 인터페이스로 주변 AP를 탐색하여 목록을 돌려준다.
	Scan(ctx context.Context, in *AccessPointScanRequest, opts ...grpc.CallOption) (*AccessPointScanResponse, error)
}

type accessPointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessPointServiceClient(cc grpc.ClientConnInterface) AccessPointServiceClient {
	return &accessPointServiceClient{cc}
}

func (c *accessPointServiceClient) Add(ctx context.Context, in *AccessPointAddRequest, opts ...grpc.CallOption) (*AccessPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessPoint)
	err := c.cc.Invoke(ctx, AccessPointService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessPointServiceClient) Get(ctx context.Context, in *AccessPointGetRequest, opts ...grpc.CallOption) (*AccessPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessPoint)
	err := c.cc.Invoke(ctx, AccessPointService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessPointServiceClient) Patch(ctx context.Context, in *AccessPointPatchRequest, opts ...grpc.CallOption) (*AccessPoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessPoint)
	err := c.cc.Invoke(ctx, AccessPointService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessPointServiceClient) Erase(ctx context.Context, in *AccessPointRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccessPointService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessPointServiceClient) Scan(ctx context.Context, in *AccessPointScanRequest, opts ...grpc.CallOption) (*AccessPointScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessPointScanResponse)
	err := c.cc.Invoke(ctx, AccessPointService_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessPointServiceServer is the server API for AccessPointService service.
// All implementations must embed UnimplementedAccessPointServiceServer
// for forward compatibility.
type AccessPointServiceServer interface {
	// Add creates a new AccessPoint
	Add(context.Context, *AccessPointAddRequest) (*AccessPoint, error)
	// Get retrieves a AccessPoint
	Get(context.Context, *AccessPointGetRequest) (*AccessPoint, error)
	// Patch updates an existing AccessPoint
	Patch(context.Context, *AccessPointPatchRequest) (*AccessPoint, error)
	// Erase deletes a AccessPoint
	Erase(context.Context, *AccessPointRef) (*emptypb.Empty, error)
	// Scan은 주어진 인터페이스로 주변 AP를 탐색하여 목록을 돌려준다.
	Scan(context.Context, *AccessPointScanRequest) (*AccessPointScanResponse, error)
	mustEmbedUnimplementedAccessPointServiceServer()
}

// UnimplementedAccessPointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessPointServiceServer struct{}

func (UnimplementedAccessPointServiceServer) Add(context.Context, *AccessPointAddRequest) (*AccessPoint, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAccessPointServiceServer) Get(context.Context, *AccessPointGetRequest) (*AccessPoint, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAccessPointServiceServer) Patch(context.Context, *AccessPointPatchRequest) (*AccessPoint, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedAccessPointServiceServer) Erase(context.Context, *AccessPointRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedAccessPointServiceServer) Scan(context.Context, *AccessPointScanRequest) (*AccessPointScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedAccessPointServiceServer) mustEmbedUnimplementedAccessPointServiceServer() {}
func (UnimplementedAccessPointServiceServer) testEmbeddedByValue()                            {}

// UnsafeAccessPointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessPointServiceServer will
// result in compilation errors.
type UnsafeAccessPointServiceServer interface {
	mustEmbedUnimplementedAccessPointServiceServer()
}

func RegisterAccessPointServiceServer(s grpc.ServiceRegistrar, srv AccessPointServiceServer) {
	// If the following call panics, it indicates UnimplementedAccessPointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessPointService_ServiceDesc, srv)
}

func _AccessPointService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessPointAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessPointServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessPointService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessPointServiceServer).Add(ctx, req.(*AccessPointAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessPointService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessPointGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessPointServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessPointService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessPointServiceServer).Get(ctx, req.(*AccessPointGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessPointService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessPointPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessPointServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessPointService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessPointServiceServer).Patch(ctx, req.(*AccessPointPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessPointService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessPointRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessPointServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessPointService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessPointServiceServer).Erase(ctx, req.(*AccessPointRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessPointService_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessPointScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessPointServiceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessPointService_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessPointServiceServer).Scan(ctx, req.(*AccessPointScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessPointService_ServiceDesc is the grpc.ServiceDesc for AccessPointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessPointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wifi.AccessPointService",
	HandlerType: (*AccessPointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AccessPointService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccessPointService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _AccessPointService_Patch_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _AccessPointService_Erase_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _AccessPointService_Scan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wifi/access_point_svc.g.proto",
}
