// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/cache.proto

package wifi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScanCache is the on-disk cache of the most recent access-point scan per
// interface. The client writes it to a ".wfm" file in the working directory so
// the UI can show the last-known networks immediately on launch, before a fresh
// scan completes.
//
// It is a plain value object, not an ORM entity: the whole message is marshaled
// to and from the file as a single blob.
type ScanCache struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Interfaces *[]*InterfaceScan      `protobuf:"bytes,1,rep,name=interfaces"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ScanCache) Reset() {
	*x = ScanCache{}
	mi := &file_wifi_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanCache) ProtoMessage() {}

func (x *ScanCache) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScanCache) GetInterfaces() []*InterfaceScan {
	if x != nil {
		if x.xxx_hidden_Interfaces != nil {
			return *x.xxx_hidden_Interfaces
		}
	}
	return nil
}

func (x *ScanCache) SetInterfaces(v []*InterfaceScan) {
	x.xxx_hidden_Interfaces = &v
}

type ScanCache_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The latest scan for each interface. At most one entry per interface id;
	// a new scan replaces the previous entry for that interface.
	Interfaces []*InterfaceScan
}

func (b0 ScanCache_builder) Build() *ScanCache {
	m0 := &ScanCache{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Interfaces = &b.Interfaces
	return m0
}

// InterfaceScan is the result of a single scan on one interface.
type InterfaceScan struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InterfaceId  *string                `protobuf:"bytes,1,opt,name=interface_id,json=interfaceId"`
	xxx_hidden_ScannedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=scanned_at,json=scannedAt"`
	xxx_hidden_AccessPoints *[]*AccessPoint        `protobuf:"bytes,3,rep,name=access_points,json=accessPoints"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InterfaceScan) Reset() {
	*x = InterfaceScan{}
	mi := &file_wifi_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceScan) ProtoMessage() {}

func (x *InterfaceScan) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceScan) GetInterfaceId() string {
	if x != nil {
		if x.xxx_hidden_InterfaceId != nil {
			return *x.xxx_hidden_InterfaceId
		}
		return ""
	}
	return ""
}

func (x *InterfaceScan) GetScannedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ScannedAt
	}
	return nil
}

func (x *InterfaceScan) GetAccessPoints() []*AccessPoint {
	if x != nil {
		if x.xxx_hidden_AccessPoints != nil {
			return *x.xxx_hidden_AccessPoints
		}
	}
	return nil
}

func (x *InterfaceScan) SetInterfaceId(v string) {
	x.xxx_hidden_InterfaceId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *InterfaceScan) SetScannedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ScannedAt = v
}

func (x *InterfaceScan) SetAccessPoints(v []*AccessPoint) {
	x.xxx_hidden_AccessPoints = &v
}

func (x *InterfaceScan) HasInterfaceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InterfaceScan) HasScannedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ScannedAt != nil
}

func (x *InterfaceScan) ClearInterfaceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_InterfaceId = nil
}

func (x *InterfaceScan) ClearScannedAt() {
	x.xxx_hidden_ScannedAt = nil
}

type InterfaceScan_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The interface the scan was performed on.
	InterfaceId *string
	// When the scan completed. Entries older than the client's cache TTL are
	// dropped when the cache is loaded.
	ScannedAt *timestamppb.Timestamp
	// The access points the scan found, as returned by AccessPointService.Scan.
	AccessPoints []*AccessPoint
}

func (b0 InterfaceScan_builder) Build() *InterfaceScan {
	m0 := &InterfaceScan{}
	b, x := &b0, m0
	_, _ = b, x
	if b.InterfaceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_InterfaceId = b.InterfaceId
	}
	x.xxx_hidden_ScannedAt = b.ScannedAt
	x.xxx_hidden_AccessPoints = &b.AccessPoints
	return m0
}

var File_wifi_cache_proto protoreflect.FileDescriptor

const file_wifi_cache_proto_rawDesc = "" +
	"\n" +
	"\x10wifi/cache.proto\x12\x04wifi\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17wifi/access_point.proto\"@\n" +
	"\tScanCache\x123\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x13.wifi.InterfaceScanR\n" +
	"interfaces\"\xa5\x01\n" +
	"\rInterfaceScan\x12!\n" +
	"\finterface_id\x18\x01 \x01(\tR\vinterfaceId\x129\n" +
	"\n" +
	"scanned_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tscannedAt\x126\n" +
	"\raccess_points\x18\x03 \x03(\v2\x11.wifi.AccessPointR\faccessPointsB'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wifi_cache_proto_goTypes = []any{
	(*ScanCache)(nil),             // 0: wifi.ScanCache
	(*InterfaceScan)(nil),         // 1: wifi.InterfaceScan
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*AccessPoint)(nil),           // 3: wifi.AccessPoint
}
var file_wifi_cache_proto_depIdxs = []int32{
	1, // 0: wifi.ScanCache.interfaces:type_name -> wifi.InterfaceScan
	2, // 1: wifi.InterfaceScan.scanned_at:type_name -> google.protobuf.Timestamp
	3, // 2: wifi.InterfaceScan.access_points:type_name -> wifi.AccessPoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wifi_cache_proto_init() }
func file_wifi_cache_proto_init() {
	if File_wifi_cache_proto != nil {
		return
	}
	file_wifi_access_point_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_cache_proto_rawDesc), len(file_wifi_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_cache_proto_goTypes,
		DependencyIndexes: file_wifi_cache_proto_depIdxs,
		MessageInfos:      file_wifi_cache_proto_msgTypes,
	}.Build()
	File_wifi_cache_proto = out.File
	file_wifi_cache_proto_goTypes = nil
	file_wifi_cache_proto_depIdxs = nil
}
