// Code generated by protoc-gen-orm-service. DO NOT EDIT.
// source: wifi/connection.proto.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/connection_svc.g.proto

package wifi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectionState는 활성 연결의 진행 상태를 나타낸다.
type ConnectionState int32

const (
	ConnectionState_CONNECTION_STATE_UNSPECIFIED ConnectionState = 0
	// 아직 시작 전.
	ConnectionState_CONNECTION_STATE_IDLE ConnectionState = 1
	// AP에 결합 중(BSS 선택/association).
	ConnectionState_CONNECTION_STATE_ASSOCIATING ConnectionState = 2
	// 보안 핸드셰이크 수행 중(예: WPA 4-way handshake).
	ConnectionState_CONNECTION_STATE_AUTHENTICATING ConnectionState = 3
	// IP 설정을 받는 중(DHCP/SLAAC).
	ConnectionState_CONNECTION_STATE_CONFIGURING ConnectionState = 4
	// 완전히 연결되어 사용 가능(성공 끝 상태).
	ConnectionState_CONNECTION_STATE_CONNECTED ConnectionState = 5
	// 연결 실패(끝 상태). 원인은 error 참고.
	ConnectionState_CONNECTION_STATE_FAILED ConnectionState = 6
	// 해제되는 중.
	ConnectionState_CONNECTION_STATE_DISCONNECTING ConnectionState = 7
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "CONNECTION_STATE_UNSPECIFIED",
		1: "CONNECTION_STATE_IDLE",
		2: "CONNECTION_STATE_ASSOCIATING",
		3: "CONNECTION_STATE_AUTHENTICATING",
		4: "CONNECTION_STATE_CONFIGURING",
		5: "CONNECTION_STATE_CONNECTED",
		6: "CONNECTION_STATE_FAILED",
		7: "CONNECTION_STATE_DISCONNECTING",
	}
	ConnectionState_value = map[string]int32{
		"CONNECTION_STATE_UNSPECIFIED":    0,
		"CONNECTION_STATE_IDLE":           1,
		"CONNECTION_STATE_ASSOCIATING":    2,
		"CONNECTION_STATE_AUTHENTICATING": 3,
		"CONNECTION_STATE_CONFIGURING":    4,
		"CONNECTION_STATE_CONNECTED":      5,
		"CONNECTION_STATE_FAILED":         6,
		"CONNECTION_STATE_DISCONNECTING":  7,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_connection_svc_g_proto_enumTypes[0].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_wifi_connection_svc_g_proto_enumTypes[0]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// ConnectionError는 연결이 실패한 원인을 설명한다.
type ConnectionError int32

const (
	ConnectionError_CONNECTION_ERROR_UNSPECIFIED ConnectionError = 0
	// 오류 없음.
	ConnectionError_CONNECTION_ERROR_NONE ConnectionError = 1
	// 인증 실패(잘못된 비밀번호/자격 증명 거부).
	ConnectionError_CONNECTION_ERROR_AUTH_FAILED ConnectionError = 2
	// 대상 SSID를 찾지 못함.
	ConnectionError_CONNECTION_ERROR_NETWORK_NOT_FOUND ConnectionError = 3
	// 결합/핸드셰이크 시간 초과.
	ConnectionError_CONNECTION_ERROR_ASSOC_TIMEOUT ConnectionError = 4
	// IP 설정(DHCP 등) 실패.
	ConnectionError_CONNECTION_ERROR_IP_CONFIG_FAILED ConnectionError = 5
	// AP에 의해 끊김 / 신호 상실.
	ConnectionError_CONNECTION_ERROR_DISCONNECTED ConnectionError = 6
	// 알 수 없는 오류.
	ConnectionError_CONNECTION_ERROR_UNKNOWN ConnectionError = 7
)

// Enum value maps for ConnectionError.
var (
	ConnectionError_name = map[int32]string{
		0: "CONNECTION_ERROR_UNSPECIFIED",
		1: "CONNECTION_ERROR_NONE",
		2: "CONNECTION_ERROR_AUTH_FAILED",
		3: "CONNECTION_ERROR_NETWORK_NOT_FOUND",
		4: "CONNECTION_ERROR_ASSOC_TIMEOUT",
		5: "CONNECTION_ERROR_IP_CONFIG_FAILED",
		6: "CONNECTION_ERROR_DISCONNECTED",
		7: "CONNECTION_ERROR_UNKNOWN",
	}
	ConnectionError_value = map[string]int32{
		"CONNECTION_ERROR_UNSPECIFIED":       0,
		"CONNECTION_ERROR_NONE":              1,
		"CONNECTION_ERROR_AUTH_FAILED":       2,
		"CONNECTION_ERROR_NETWORK_NOT_FOUND": 3,
		"CONNECTION_ERROR_ASSOC_TIMEOUT":     4,
		"CONNECTION_ERROR_IP_CONFIG_FAILED":  5,
		"CONNECTION_ERROR_DISCONNECTED":      6,
		"CONNECTION_ERROR_UNKNOWN":           7,
	}
)

func (x ConnectionError) Enum() *ConnectionError {
	p := new(ConnectionError)
	*p = x
	return p
}

func (x ConnectionError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionError) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_connection_svc_g_proto_enumTypes[1].Descriptor()
}

func (ConnectionError) Type() protoreflect.EnumType {
	return &file_wifi_connection_svc_g_proto_enumTypes[1]
}

func (x ConnectionError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ConnectionAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Interface   *InterfaceRef          `protobuf:"bytes,8,opt,name=interface"`
	xxx_hidden_Profile     *ProfileRef            `protobuf:"bytes,9,opt,name=profile"`
	xxx_hidden_AccessPoint *AccessPointRef        `protobuf:"bytes,10,opt,name=access_point,json=accessPoint"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConnectionAddRequest) Reset() {
	*x = ConnectionAddRequest{}
	mi := &file_wifi_connection_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionAddRequest) ProtoMessage() {}

func (x *ConnectionAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *ConnectionAddRequest) GetInterface() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Interface
	}
	return nil
}

func (x *ConnectionAddRequest) GetProfile() *ProfileRef {
	if x != nil {
		return x.xxx_hidden_Profile
	}
	return nil
}

func (x *ConnectionAddRequest) GetAccessPoint() *AccessPointRef {
	if x != nil {
		return x.xxx_hidden_AccessPoint
	}
	return nil
}

func (x *ConnectionAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ConnectionAddRequest) SetInterface(v *InterfaceRef) {
	x.xxx_hidden_Interface = v
}

func (x *ConnectionAddRequest) SetProfile(v *ProfileRef) {
	x.xxx_hidden_Profile = v
}

func (x *ConnectionAddRequest) SetAccessPoint(v *AccessPointRef) {
	x.xxx_hidden_AccessPoint = v
}

func (x *ConnectionAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConnectionAddRequest) HasInterface() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Interface != nil
}

func (x *ConnectionAddRequest) HasProfile() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Profile != nil
}

func (x *ConnectionAddRequest) HasAccessPoint() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessPoint != nil
}

func (x *ConnectionAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ConnectionAddRequest) ClearInterface() {
	x.xxx_hidden_Interface = nil
}

func (x *ConnectionAddRequest) ClearProfile() {
	x.xxx_hidden_Profile = nil
}

func (x *ConnectionAddRequest) ClearAccessPoint() {
	x.xxx_hidden_AccessPoint = nil
}

type ConnectionAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Interface   *InterfaceRef
	Profile     *ProfileRef
	AccessPoint *AccessPointRef
}

func (b0 ConnectionAddRequest_builder) Build() *ConnectionAddRequest {
	m0 := &ConnectionAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Interface = b.Interface
	x.xxx_hidden_Profile = b.Profile
	x.xxx_hidden_AccessPoint = b.AccessPoint
	return m0
}

type ConnectionRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isConnectionRef_Key    `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionRef) Reset() {
	*x = ConnectionRef{}
	mi := &file_wifi_connection_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRef) ProtoMessage() {}

func (x *ConnectionRef) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*connectionRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *ConnectionRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &connectionRef_Id{v}
}

func (x *ConnectionRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *ConnectionRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*connectionRef_Id)
	return ok
}

func (x *ConnectionRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *ConnectionRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*connectionRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

const ConnectionRef_Key_not_set_case case_ConnectionRef_Key = 0
const ConnectionRef_Id_case case_ConnectionRef_Key = 1

func (x *ConnectionRef) WhichKey() case_ConnectionRef_Key {
	if x == nil {
		return ConnectionRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *connectionRef_Id:
		return ConnectionRef_Id_case
	default:
		return ConnectionRef_Key_not_set_case
	}
}

type ConnectionRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id []byte
	// -- end of xxx_hidden_Key
}

func (b0 ConnectionRef_builder) Build() *ConnectionRef {
	m0 := &ConnectionRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &connectionRef_Id{b.Id}
	}
	return m0
}

type case_ConnectionRef_Key protoreflect.FieldNumber

func (x case_ConnectionRef_Key) String() string {
	md := file_wifi_connection_svc_g_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isConnectionRef_Key interface {
	isConnectionRef_Key()
}

type connectionRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

func (*connectionRef_Id) isConnectionRef_Key() {}

type ConnectionSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Interface   *InterfaceSelect       `protobuf:"bytes,8,opt,name=interface"`
	xxx_hidden_Profile     *ProfileSelect         `protobuf:"bytes,9,opt,name=profile"`
	xxx_hidden_AccessPoint *AccessPointSelect     `protobuf:"bytes,10,opt,name=access_point,json=accessPoint"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConnectionSelect) Reset() {
	*x = ConnectionSelect{}
	mi := &file_wifi_connection_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSelect) ProtoMessage() {}

func (x *ConnectionSelect) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *ConnectionSelect) GetInterface() *InterfaceSelect {
	if x != nil {
		return x.xxx_hidden_Interface
	}
	return nil
}

func (x *ConnectionSelect) GetProfile() *ProfileSelect {
	if x != nil {
		return x.xxx_hidden_Profile
	}
	return nil
}

func (x *ConnectionSelect) GetAccessPoint() *AccessPointSelect {
	if x != nil {
		return x.xxx_hidden_AccessPoint
	}
	return nil
}

func (x *ConnectionSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ConnectionSelect) SetInterface(v *InterfaceSelect) {
	x.xxx_hidden_Interface = v
}

func (x *ConnectionSelect) SetProfile(v *ProfileSelect) {
	x.xxx_hidden_Profile = v
}

func (x *ConnectionSelect) SetAccessPoint(v *AccessPointSelect) {
	x.xxx_hidden_AccessPoint = v
}

func (x *ConnectionSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConnectionSelect) HasInterface() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Interface != nil
}

func (x *ConnectionSelect) HasProfile() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Profile != nil
}

func (x *ConnectionSelect) HasAccessPoint() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessPoint != nil
}

func (x *ConnectionSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *ConnectionSelect) ClearInterface() {
	x.xxx_hidden_Interface = nil
}

func (x *ConnectionSelect) ClearProfile() {
	x.xxx_hidden_Profile = nil
}

func (x *ConnectionSelect) ClearAccessPoint() {
	x.xxx_hidden_AccessPoint = nil
}

type ConnectionSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Interface   *InterfaceSelect
	Profile     *ProfileSelect
	AccessPoint *AccessPointSelect
}

func (b0 ConnectionSelect_builder) Build() *ConnectionSelect {
	m0 := &ConnectionSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Interface = b.Interface
	x.xxx_hidden_Profile = b.Profile
	x.xxx_hidden_AccessPoint = b.AccessPoint
	return m0
}

type ConnectionGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *ConnectionRef         `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *ConnectionSelect      `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectionGetRequest) Reset() {
	*x = ConnectionGetRequest{}
	mi := &file_wifi_connection_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionGetRequest) ProtoMessage() {}

func (x *ConnectionGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionGetRequest) GetRef() *ConnectionRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ConnectionGetRequest) GetSelect() *ConnectionSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *ConnectionGetRequest) SetRef(v *ConnectionRef) {
	x.xxx_hidden_Ref = v
}

func (x *ConnectionGetRequest) SetSelect(v *ConnectionSelect) {
	x.xxx_hidden_Select = v
}

func (x *ConnectionGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ConnectionGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *ConnectionGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ConnectionGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type ConnectionGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *ConnectionRef
	Select *ConnectionSelect
}

func (b0 ConnectionGetRequest_builder) Build() *ConnectionGetRequest {
	m0 := &ConnectionGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type ConnectionPatchRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref *ConnectionRef         `protobuf:"bytes,1,opt,name=ref"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectionPatchRequest) Reset() {
	*x = ConnectionPatchRequest{}
	mi := &file_wifi_connection_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionPatchRequest) ProtoMessage() {}

func (x *ConnectionPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionPatchRequest) GetRef() *ConnectionRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ConnectionPatchRequest) SetRef(v *ConnectionRef) {
	x.xxx_hidden_Ref = v
}

func (x *ConnectionPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ConnectionPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

type ConnectionPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref *ConnectionRef
}

func (b0 ConnectionPatchRequest_builder) Build() *ConnectionPatchRequest {
	m0 := &ConnectionPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	return m0
}

type ConnectionListRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Interface *InterfaceRef          `protobuf:"bytes,1,opt,name=interface"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConnectionListRequest) Reset() {
	*x = ConnectionListRequest{}
	mi := &file_wifi_connection_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionListRequest) ProtoMessage() {}

func (x *ConnectionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionListRequest) GetInterface() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Interface
	}
	return nil
}

func (x *ConnectionListRequest) SetInterface(v *InterfaceRef) {
	x.xxx_hidden_Interface = v
}

func (x *ConnectionListRequest) HasInterface() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Interface != nil
}

func (x *ConnectionListRequest) ClearInterface() {
	x.xxx_hidden_Interface = nil
}

type ConnectionListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 지정하면 해당 인터페이스의 연결만 돌려준다(선택).
	Interface *InterfaceRef
}

func (b0 ConnectionListRequest_builder) Build() *ConnectionListRequest {
	m0 := &ConnectionListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Interface = b.Interface
	return m0
}

type ConnectionListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Connection         `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionListResponse) Reset() {
	*x = ConnectionListResponse{}
	mi := &file_wifi_connection_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionListResponse) ProtoMessage() {}

func (x *ConnectionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionListResponse) GetItems() []*Connection {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ConnectionListResponse) SetItems(v []*Connection) {
	x.xxx_hidden_Items = &v
}

type ConnectionListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 활성 연결 목록.
	Items []*Connection
}

func (b0 ConnectionListResponse_builder) Build() *ConnectionListResponse {
	m0 := &ConnectionListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

// ConnectionStatus는 활성 연결의 실시간 상태 스냅샷이다.
//
// 연결이 유지되는 동안 계속 변하므로 Connection 엔티티에 저장하지 않고
// Watch/GetStatus를 통해 별도로 전달한다.
type ConnectionStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State       ConnectionState        `protobuf:"varint,1,opt,name=state,enum=wifi.ConnectionState"`
	xxx_hidden_Error       ConnectionError        `protobuf:"varint,2,opt,name=error,enum=wifi.ConnectionError"`
	xxx_hidden_Detail      *string                `protobuf:"bytes,3,opt,name=detail"`
	xxx_hidden_Bssid       *string                `protobuf:"bytes,4,opt,name=bssid"`
	xxx_hidden_Signal      int32                  `protobuf:"varint,5,opt,name=signal"`
	xxx_hidden_Addresses   []string               `protobuf:"bytes,6,rep,name=addresses"`
	xxx_hidden_Gateway     *string                `protobuf:"bytes,7,opt,name=gateway"`
	xxx_hidden_Dns         []string               `protobuf:"bytes,8,rep,name=dns"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_wifi_connection_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionStatus) GetState() ConnectionState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_State
		}
	}
	return ConnectionState_CONNECTION_STATE_UNSPECIFIED
}

func (x *ConnectionStatus) GetError() ConnectionError {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Error
		}
	}
	return ConnectionError_CONNECTION_ERROR_UNSPECIFIED
}

func (x *ConnectionStatus) GetDetail() string {
	if x != nil {
		if x.xxx_hidden_Detail != nil {
			return *x.xxx_hidden_Detail
		}
		return ""
	}
	return ""
}

func (x *ConnectionStatus) GetBssid() string {
	if x != nil {
		if x.xxx_hidden_Bssid != nil {
			return *x.xxx_hidden_Bssid
		}
		return ""
	}
	return ""
}

func (x *ConnectionStatus) GetSignal() int32 {
	if x != nil {
		return x.xxx_hidden_Signal
	}
	return 0
}

func (x *ConnectionStatus) GetAddresses() []string {
	if x != nil {
		return x.xxx_hidden_Addresses
	}
	return nil
}

func (x *ConnectionStatus) GetGateway() string {
	if x != nil {
		if x.xxx_hidden_Gateway != nil {
			return *x.xxx_hidden_Gateway
		}
		return ""
	}
	return ""
}

func (x *ConnectionStatus) GetDns() []string {
	if x != nil {
		return x.xxx_hidden_Dns
	}
	return nil
}

func (x *ConnectionStatus) SetState(v ConnectionState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *ConnectionStatus) SetError(v ConnectionError) {
	x.xxx_hidden_Error = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *ConnectionStatus) SetDetail(v string) {
	x.xxx_hidden_Detail = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *ConnectionStatus) SetBssid(v string) {
	x.xxx_hidden_Bssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *ConnectionStatus) SetSignal(v int32) {
	x.xxx_hidden_Signal = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *ConnectionStatus) SetAddresses(v []string) {
	x.xxx_hidden_Addresses = v
}

func (x *ConnectionStatus) SetGateway(v string) {
	x.xxx_hidden_Gateway = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *ConnectionStatus) SetDns(v []string) {
	x.xxx_hidden_Dns = v
}

func (x *ConnectionStatus) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConnectionStatus) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConnectionStatus) HasDetail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ConnectionStatus) HasBssid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ConnectionStatus) HasSignal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ConnectionStatus) HasGateway() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ConnectionStatus) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_State = ConnectionState_CONNECTION_STATE_UNSPECIFIED
}

func (x *ConnectionStatus) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = ConnectionError_CONNECTION_ERROR_UNSPECIFIED
}

func (x *ConnectionStatus) ClearDetail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Detail = nil
}

func (x *ConnectionStatus) ClearBssid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Bssid = nil
}

func (x *ConnectionStatus) ClearSignal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Signal = 0
}

func (x *ConnectionStatus) ClearGateway() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Gateway = nil
}

type ConnectionStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 현재 진행 상태.
	State *ConnectionState
	// state == FAILED 일 때 설정되는 실패 원인.
	Error *ConnectionError
	// 현재 상태/오류에 대한 사람이 읽을 수 있는 부가 설명(선택).
	Detail *string
	// 현재 결합된 AP의 BSSID. 로밍 시 바뀔 수 있다.
	Bssid *string
	// 현재 신호 품질(0-100). 클수록 강하다(NetworkManager Strength와 동일 척도).
	Signal *int32
	// 연결 후 실제로 할당된 주소들(CIDR 표기).
	Addresses []string
	// 실제 적용된 기본 게이트웨이.
	Gateway *string
	// 실제 적용된 DNS 서버들.
	Dns []string
}

func (b0 ConnectionStatus_builder) Build() *ConnectionStatus {
	m0 := &ConnectionStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_State = *b.State
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Error = *b.Error
	}
	if b.Detail != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Detail = b.Detail
	}
	if b.Bssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Bssid = b.Bssid
	}
	if b.Signal != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Signal = *b.Signal
	}
	x.xxx_hidden_Addresses = b.Addresses
	if b.Gateway != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Gateway = b.Gateway
	}
	x.xxx_hidden_Dns = b.Dns
	return m0
}

var File_wifi_connection_svc_g_proto protoreflect.FileDescriptor

const file_wifi_connection_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x1bwifi/connection_svc.g.proto\x12\x04wifi\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dwifi/access_point_svc.g.proto\x1a\x15wifi/connection.proto\x1a\x1awifi/interface_svc.g.proto\x1a\x18wifi/profile_svc.g.proto\"\xbd\x01\n" +
	"\x14ConnectionAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x120\n" +
	"\tinterface\x18\b \x01(\v2\x12.wifi.InterfaceRefR\tinterface\x12*\n" +
	"\aprofile\x18\t \x01(\v2\x10.wifi.ProfileRefR\aprofile\x127\n" +
	"\faccess_point\x18\n" +
	" \x01(\v2\x14.wifi.AccessPointRefR\vaccessPoint\"(\n" +
	"\rConnectionRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02idB\x05\n" +
	"\x03key\"\xc4\x01\n" +
	"\x10ConnectionSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x123\n" +
	"\tinterface\x18\b \x01(\v2\x15.wifi.InterfaceSelectR\tinterface\x12-\n" +
	"\aprofile\x18\t \x01(\v2\x13.wifi.ProfileSelectR\aprofile\x12:\n" +
	"\faccess_point\x18\n" +
	" \x01(\v2\x17.wifi.AccessPointSelectR\vaccessPoint\"m\n" +
	"\x14ConnectionGetRequest\x12%\n" +
	"\x03ref\x18\x01 \x01(\v2\x13.wifi.ConnectionRefR\x03ref\x12.\n" +
	"\x06select\x18\x02 \x01(\v2\x16.wifi.ConnectionSelectR\x06select\"?\n" +
	"\x16ConnectionPatchRequest\x12%\n" +
	"\x03ref\x18\x01 \x01(\v2\x13.wifi.ConnectionRefR\x03ref\"I\n" +
	"\x15ConnectionListRequest\x120\n" +
	"\tinterface\x18\x01 \x01(\v2\x12.wifi.InterfaceRefR\tinterface\"@\n" +
	"\x16ConnectionListResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.wifi.ConnectionR\x05items\"\xfc\x01\n" +
	"\x10ConnectionStatus\x12+\n" +
	"\x05state\x18\x01 \x01(\x0e2\x15.wifi.ConnectionStateR\x05state\x12+\n" +
	"\x05error\x18\x02 \x01(\x0e2\x15.wifi.ConnectionErrorR\x05error\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x14\n" +
	"\x05bssid\x18\x04 \x01(\tR\x05bssid\x12\x16\n" +
	"\x06signal\x18\x05 \x01(\x05R\x06signal\x12\x1c\n" +
	"\taddresses\x18\x06 \x03(\tR\taddresses\x12\x18\n" +
	"\agateway\x18\a \x01(\tR\agateway\x12\x10\n" +
	"\x03dns\x18\b \x03(\tR\x03dns*\x98\x02\n" +
	"\x0fConnectionState\x12 \n" +
	"\x1cCONNECTION_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONNECTION_STATE_IDLE\x10\x01\x12 \n" +
	"\x1cCONNECTION_STATE_ASSOCIATING\x10\x02\x12#\n" +
	"\x1fCONNECTION_STATE_AUTHENTICATING\x10\x03\x12 \n" +
	"\x1cCONNECTION_STATE_CONFIGURING\x10\x04\x12\x1e\n" +
	"\x1aCONNECTION_STATE_CONNECTED\x10\x05\x12\x1b\n" +
	"\x17CONNECTION_STATE_FAILED\x10\x06\x12\"\n" +
	"\x1eCONNECTION_STATE_DISCONNECTING\x10\a*\xa4\x02\n" +
	"\x0fConnectionError\x12 \n" +
	"\x1cCONNECTION_ERROR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONNECTION_ERROR_NONE\x10\x01\x12 \n" +
	"\x1cCONNECTION_ERROR_AUTH_FAILED\x10\x02\x12&\n" +
	"\"CONNECTION_ERROR_NETWORK_NOT_FOUND\x10\x03\x12\"\n" +
	"\x1eCONNECTION_ERROR_ASSOC_TIMEOUT\x10\x04\x12%\n" +
	"!CONNECTION_ERROR_IP_CONFIG_FAILED\x10\x05\x12!\n" +
	"\x1dCONNECTION_ERROR_DISCONNECTED\x10\x06\x12\x1c\n" +
	"\x18CONNECTION_ERROR_UNKNOWN\x10\a2\xa1\x03\n" +
	"\x11ConnectionService\x123\n" +
	"\x03Add\x12\x1a.wifi.ConnectionAddRequest\x1a\x10.wifi.Connection\x123\n" +
	"\x03Get\x12\x1a.wifi.ConnectionGetRequest\x1a\x10.wifi.Connection\x127\n" +
	"\x05Patch\x12\x1c.wifi.ConnectionPatchRequest\x1a\x10.wifi.Connection\x124\n" +
	"\x05Erase\x12\x13.wifi.ConnectionRef\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x04List\x12\x1b.wifi.ConnectionListRequest\x1a\x1c.wifi.ConnectionListResponse\x126\n" +
	"\x05Watch\x12\x13.wifi.ConnectionRef\x1a\x16.wifi.ConnectionStatus0\x01\x128\n" +
	"\tGetStatus\x12\x13.wifi.ConnectionRef\x1a\x16.wifi.ConnectionStatusB'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_connection_svc_g_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wifi_connection_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wifi_connection_svc_g_proto_goTypes = []any{
	(ConnectionState)(0),           // 0: wifi.ConnectionState
	(ConnectionError)(0),           // 1: wifi.ConnectionError
	(*ConnectionAddRequest)(nil),   // 2: wifi.ConnectionAddRequest
	(*ConnectionRef)(nil),          // 3: wifi.ConnectionRef
	(*ConnectionSelect)(nil),       // 4: wifi.ConnectionSelect
	(*ConnectionGetRequest)(nil),   // 5: wifi.ConnectionGetRequest
	(*ConnectionPatchRequest)(nil), // 6: wifi.ConnectionPatchRequest
	(*ConnectionListRequest)(nil),  // 7: wifi.ConnectionListRequest
	(*ConnectionListResponse)(nil), // 8: wifi.ConnectionListResponse
	(*ConnectionStatus)(nil),       // 9: wifi.ConnectionStatus
	(*InterfaceRef)(nil),           // 10: wifi.InterfaceRef
	(*ProfileRef)(nil),             // 11: wifi.ProfileRef
	(*AccessPointRef)(nil),         // 12: wifi.AccessPointRef
	(*InterfaceSelect)(nil),        // 13: wifi.InterfaceSelect
	(*ProfileSelect)(nil),          // 14: wifi.ProfileSelect
	(*AccessPointSelect)(nil),      // 15: wifi.AccessPointSelect
	(*Connection)(nil),             // 16: wifi.Connection
	(*emptypb.Empty)(nil),          // 17: google.protobuf.Empty
}
var file_wifi_connection_svc_g_proto_depIdxs = []int32{
	10, // 0: wifi.ConnectionAddRequest.interface:type_name -> wifi.InterfaceRef
	11, // 1: wifi.ConnectionAddRequest.profile:type_name -> wifi.ProfileRef
	12, // 2: wifi.ConnectionAddRequest.access_point:type_name -> wifi.AccessPointRef
	13, // 3: wifi.ConnectionSelect.interface:type_name -> wifi.InterfaceSelect
	14, // 4: wifi.ConnectionSelect.profile:type_name -> wifi.ProfileSelect
	15, // 5: wifi.ConnectionSelect.access_point:type_name -> wifi.AccessPointSelect
	3,  // 6: wifi.ConnectionGetRequest.ref:type_name -> wifi.ConnectionRef
	4,  // 7: wifi.ConnectionGetRequest.select:type_name -> wifi.ConnectionSelect
	3,  // 8: wifi.ConnectionPatchRequest.ref:type_name -> wifi.ConnectionRef
	10, // 9: wifi.ConnectionListRequest.interface:type_name -> wifi.InterfaceRef
	16, // 10: wifi.ConnectionListResponse.items:type_name -> wifi.Connection
	0,  // 11: wifi.ConnectionStatus.state:type_name -> wifi.ConnectionState
	1,  // 12: wifi.ConnectionStatus.error:type_name -> wifi.ConnectionError
	2,  // 13: wifi.ConnectionService.Add:input_type -> wifi.ConnectionAddRequest
	5,  // 14: wifi.ConnectionService.Get:input_type -> wifi.ConnectionGetRequest
	6,  // 15: wifi.ConnectionService.Patch:input_type -> wifi.ConnectionPatchRequest
	3,  // 16: wifi.ConnectionService.Erase:input_type -> wifi.ConnectionRef
	7,  // 17: wifi.ConnectionService.List:input_type -> wifi.ConnectionListRequest
	3,  // 18: wifi.ConnectionService.Watch:input_type -> wifi.ConnectionRef
	3,  // 19: wifi.ConnectionService.GetStatus:input_type -> wifi.ConnectionRef
	16, // 20: wifi.ConnectionService.Add:output_type -> wifi.Connection
	16, // 21: wifi.ConnectionService.Get:output_type -> wifi.Connection
	16, // 22: wifi.ConnectionService.Patch:output_type -> wifi.Connection
	17, // 23: wifi.ConnectionService.Erase:output_type -> google.protobuf.Empty
	8,  // 24: wifi.ConnectionService.List:output_type -> wifi.ConnectionListResponse
	9,  // 25: wifi.ConnectionService.Watch:output_type -> wifi.ConnectionStatus
	9,  // 26: wifi.ConnectionService.GetStatus:output_type -> wifi.ConnectionStatus
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_wifi_connection_svc_g_proto_init() }
func file_wifi_connection_svc_g_proto_init() {
	if File_wifi_connection_svc_g_proto != nil {
		return
	}
	file_wifi_access_point_svc_g_proto_init()
	file_wifi_connection_proto_init()
	file_wifi_interface_svc_g_proto_init()
	file_wifi_profile_svc_g_proto_init()
	file_wifi_connection_svc_g_proto_msgTypes[1].OneofWrappers = []any{
		(*connectionRef_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_connection_svc_g_proto_rawDesc), len(file_wifi_connection_svc_g_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wifi_connection_svc_g_proto_goTypes,
		DependencyIndexes: file_wifi_connection_svc_g_proto_depIdxs,
		EnumInfos:         file_wifi_connection_svc_g_proto_enumTypes,
		MessageInfos:      file_wifi_connection_svc_g_proto_msgTypes,
	}.Build()
	File_wifi_connection_svc_g_proto = out.File
	file_wifi_connection_svc_g_proto_goTypes = nil
	file_wifi_connection_svc_g_proto_depIdxs = nil
}
