// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/connection.proto

package wifi

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Connection은 "지금 활성화되어 있는 연결" 하나를 나타낸다.
//
// Add는 주어진 Interface에 Profile을 적용해 새 연결을 활성화하고,
// Erase는 활성 연결을 해제한다. 하나의 Interface 위에는 동시에 둘 이상의
// Connection이 존재할 수 없다(라디오는 한 번에 한 네트워크에만 붙는다).
// "수정" 개념은 없고(설정을 바꾸려면 해제 후 재활성화한다) Patch도 의미상
// 맞지 않지만, 테스트(mock 등)의 편의를 위해 CRUD를 모두 정의해 둔다.
// 실제 서비스 구현은 Patch에 대해 unimplemented를 반환한다.
//
// 이 메세지는 연결의 *정체성*(어떤 인터페이스/프로파일 조합인지)만 담는다.
// 연결 진행 상태나 할당된 IP 같은 실시간 정보는 계속 변하므로 엔티티
// 필드로 저장하지 않고, ConnectionService.Watch/GetStatus가 돌려주는
// ConnectionStatus로 전달한다(connection_svc.ext.proto 참고).
type Connection struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Interface   *Interface             `protobuf:"bytes,8,opt,name=interface"`
	xxx_hidden_Profile     *Profile               `protobuf:"bytes,9,opt,name=profile"`
	xxx_hidden_AccessPoint *AccessPoint           `protobuf:"bytes,10,opt,name=access_point,json=accessPoint"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_wifi_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Connection) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Connection) GetInterface() *Interface {
	if x != nil {
		return x.xxx_hidden_Interface
	}
	return nil
}

func (x *Connection) GetProfile() *Profile {
	if x != nil {
		return x.xxx_hidden_Profile
	}
	return nil
}

func (x *Connection) GetAccessPoint() *AccessPoint {
	if x != nil {
		return x.xxx_hidden_AccessPoint
	}
	return nil
}

func (x *Connection) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Connection) SetInterface(v *Interface) {
	x.xxx_hidden_Interface = v
}

func (x *Connection) SetProfile(v *Profile) {
	x.xxx_hidden_Profile = v
}

func (x *Connection) SetAccessPoint(v *AccessPoint) {
	x.xxx_hidden_AccessPoint = v
}

func (x *Connection) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Connection) HasInterface() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Interface != nil
}

func (x *Connection) HasProfile() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Profile != nil
}

func (x *Connection) HasAccessPoint() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessPoint != nil
}

func (x *Connection) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Connection) ClearInterface() {
	x.xxx_hidden_Interface = nil
}

func (x *Connection) ClearProfile() {
	x.xxx_hidden_Profile = nil
}

func (x *Connection) ClearAccessPoint() {
	x.xxx_hidden_AccessPoint = nil
}

type Connection_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 연결 식별자(자동 생성 UUID).
	Id []byte
	// 이 연결이 사용하는 무선 인터페이스. 활성화 후에는 바꿀 수 없다.
	Interface *Interface
	// 이 연결에 적용된 프로파일(자격 증명/IP 설정 등). 바꿀 수 없다.
	Profile *Profile
	// 연결을 특정 AP(BSS)에 고정하고 싶을 때 지정한다. 지정하지 않으면
	// 같은 SSID 중 시스템이 적절한 AP를 선택한다(로밍 포함).
	AccessPoint *AccessPoint
}

func (b0 Connection_builder) Build() *Connection {
	m0 := &Connection{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Interface = b.Interface
	x.xxx_hidden_Profile = b.Profile
	x.xxx_hidden_AccessPoint = b.AccessPoint
	return m0
}

var File_wifi_connection_proto protoreflect.FileDescriptor

const file_wifi_connection_proto_rawDesc = "" +
	"\n" +
	"\x15wifi/connection.proto\x12\x04wifi\x1a\torm.proto\x1a\x17wifi/access_point.proto\x1a\x14wifi/interface.proto\x1a\x12wifi/profile.proto\"\xdb\x01\n" +
	"\n" +
	"Connection\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x125\n" +
	"\tinterface\x18\b \x01(\v2\x0f.wifi.InterfaceB\x06\xf2\x82\x16\x02@\x01R\tinterface\x12/\n" +
	"\aprofile\x18\t \x01(\v2\r.wifi.ProfileB\x06\xf2\x82\x16\x02@\x01R\aprofile\x12>\n" +
	"\faccess_point\x18\n" +
	" \x01(\v2\x11.wifi.AccessPointB\b\xf2\x82\x16\x048\x01@\x01R\vaccessPoint:\b\xca\xfc\x15\x04\x12\x02\x10\x01B'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wifi_connection_proto_goTypes = []any{
	(*Connection)(nil),  // 0: wifi.Connection
	(*Interface)(nil),   // 1: wifi.Interface
	(*Profile)(nil),     // 2: wifi.Profile
	(*AccessPoint)(nil), // 3: wifi.AccessPoint
}
var file_wifi_connection_proto_depIdxs = []int32{
	1, // 0: wifi.Connection.interface:type_name -> wifi.Interface
	2, // 1: wifi.Connection.profile:type_name -> wifi.Profile
	3, // 2: wifi.Connection.access_point:type_name -> wifi.AccessPoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wifi_connection_proto_init() }
func file_wifi_connection_proto_init() {
	if File_wifi_connection_proto != nil {
		return
	}
	file_wifi_access_point_proto_init()
	file_wifi_interface_proto_init()
	file_wifi_profile_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_connection_proto_rawDesc), len(file_wifi_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_connection_proto_goTypes,
		DependencyIndexes: file_wifi_connection_proto_depIdxs,
		MessageInfos:      file_wifi_connection_proto_msgTypes,
	}.Build()
	File_wifi_connection_proto = out.File
	file_wifi_connection_proto_goTypes = nil
	file_wifi_connection_proto_depIdxs = nil
}
