// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: wifi/connection_svc.g.proto

package wifi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectionService_Add_FullMethodName       = "/wifi.ConnectionService/Add"
	ConnectionService_Get_FullMethodName       = "/wifi.ConnectionService/Get"
	ConnectionService_Patch_FullMethodName     = "/wifi.ConnectionService/Patch"
	ConnectionService_Erase_FullMethodName     = "/wifi.ConnectionService/Erase"
	ConnectionService_List_FullMethodName      = "/wifi.ConnectionService/List"
	ConnectionService_Watch_FullMethodName     = "/wifi.ConnectionService/Watch"
	ConnectionService_GetStatus_FullMethodName = "/wifi.ConnectionService/GetStatus"
)

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectionServiceClient interface {
	// Add creates a new Connection
	Add(ctx context.Context, in *ConnectionAddRequest, opts ...grpc.CallOption) (*Connection, error)
	// Get retrieves a Connection
	Get(ctx context.Context, in *ConnectionGetRequest, opts ...grpc.CallOption) (*Connection, error)
	// Patch updates an existing Connection
	Patch(ctx context.Context, in *ConnectionPatchRequest, opts ...grpc.CallOption) (*Connection, error)
	// Erase deletes a Connection
	Erase(ctx context.Context, in *ConnectionRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List enumerates the currently active connections.
	List(ctx context.Context, in *ConnectionListRequest, opts ...grpc.CallOption) (*ConnectionListResponse, error)
	// Watch streams state changes until the connection reaches a terminal state
	// (CONNECTED or FAILED). It is the core of the "enter the password and wait
	// to be connected" flow; results such as an authentication failure (wrong
	// password) are also delivered through this stream.
	Watch(ctx context.Context, in *ConnectionRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionStatus], error)
	// GetStatus queries the current state of a connection once (a snapshot).
	GetStatus(ctx context.Context, in *ConnectionRef, opts ...grpc.CallOption) (*ConnectionStatus, error)
}

type connectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionServiceClient(cc grpc.ClientConnInterface) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) Add(ctx context.Context, in *ConnectionAddRequest, opts ...grpc.CallOption) (*Connection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connection)
	err := c.cc.Invoke(ctx, ConnectionService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) Get(ctx context.Context, in *ConnectionGetRequest, opts ...grpc.CallOption) (*Connection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connection)
	err := c.cc.Invoke(ctx, ConnectionService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) Patch(ctx context.Context, in *ConnectionPatchRequest, opts ...grpc.CallOption) (*Connection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connection)
	err := c.cc.Invoke(ctx, ConnectionService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) Erase(ctx context.Context, in *ConnectionRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ConnectionService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) List(ctx context.Context, in *ConnectionListRequest, opts ...grpc.CallOption) (*ConnectionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionListResponse)
	err := c.cc.Invoke(ctx, ConnectionService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) Watch(ctx context.Context, in *ConnectionRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectionService_ServiceDesc.Streams[0], ConnectionService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectionRef, ConnectionStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionService_WatchClient = grpc.ServerStreamingClient[ConnectionStatus]

func (c *connectionServiceClient) GetStatus(ctx context.Context, in *ConnectionRef, opts ...grpc.CallOption) (*ConnectionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionStatus)
	err := c.cc.Invoke(ctx, ConnectionService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
// All implementations must embed UnimplementedConnectionServiceServer
// for forward compatibility.
type ConnectionServiceServer interface {
	// Add creates a new Connection
	Add(context.Context, *ConnectionAddRequest) (*Connection, error)
	// Get retrieves a Connection
	Get(context.Context, *ConnectionGetRequest) (*Connection, error)
	// Patch updates an existing Connection
	Patch(context.Context, *ConnectionPatchRequest) (*Connection, error)
	// Erase deletes a Connection
	Erase(context.Context, *ConnectionRef) (*emptypb.Empty, error)
	// List enumerates the currently active connections.
	List(context.Context, *ConnectionListRequest) (*ConnectionListResponse, error)
	// Watch streams state changes until the connection reaches a terminal state
	// (CONNECTED or FAILED). It is the core of the "enter the password and wait
	// to be connected" flow; results such as an authentication failure (wrong
	// password) are also delivered through this stream.
	Watch(*ConnectionRef, grpc.ServerStreamingServer[ConnectionStatus]) error
	// GetStatus queries the current state of a connection once (a snapshot).
	GetStatus(context.Context, *ConnectionRef) (*ConnectionStatus, error)
	mustEmbedUnimplementedConnectionServiceServer()
}

// UnimplementedConnectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectionServiceServer struct{}

func (UnimplementedConnectionServiceServer) Add(context.Context, *ConnectionAddRequest) (*Connection, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedConnectionServiceServer) Get(context.Context, *ConnectionGetRequest) (*Connection, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedConnectionServiceServer) Patch(context.Context, *ConnectionPatchRequest) (*Connection, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedConnectionServiceServer) Erase(context.Context, *ConnectionRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedConnectionServiceServer) List(context.Context, *ConnectionListRequest) (*ConnectionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedConnectionServiceServer) Watch(*ConnectionRef, grpc.ServerStreamingServer[ConnectionStatus]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedConnectionServiceServer) GetStatus(context.Context, *ConnectionRef) (*ConnectionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedConnectionServiceServer) mustEmbedUnimplementedConnectionServiceServer() {}
func (UnimplementedConnectionServiceServer) testEmbeddedByValue()                           {}

// UnsafeConnectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectionServiceServer will
// result in compilation errors.
type UnsafeConnectionServiceServer interface {
	mustEmbedUnimplementedConnectionServiceServer()
}

func RegisterConnectionServiceServer(s grpc.ServiceRegistrar, srv ConnectionServiceServer) {
	// If the following call panics, it indicates UnimplementedConnectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectionService_ServiceDesc, srv)
}

func _ConnectionService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).Add(ctx, req.(*ConnectionAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).Get(ctx, req.(*ConnectionGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).Patch(ctx, req.(*ConnectionPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).Erase(ctx, req.(*ConnectionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).List(ctx, req.(*ConnectionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectionRef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectionServiceServer).Watch(m, &grpc.GenericServerStream[ConnectionRef, ConnectionStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectionService_WatchServer = grpc.ServerStreamingServer[ConnectionStatus]

func _ConnectionService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectionService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).GetStatus(ctx, req.(*ConnectionRef))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectionService_ServiceDesc is the grpc.ServiceDesc for ConnectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wifi.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _ConnectionService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ConnectionService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _ConnectionService_Patch_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _ConnectionService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ConnectionService_List_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ConnectionService_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _ConnectionService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "wifi/connection_svc.g.proto",
}
