// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/connection.proto

package wifi

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Connection represents a single "currently active connection".
//
// Add activates a new connection by applying a Profile to a given Interface,
// and Erase tears down an active connection. No more than one Connection can
// exist on a single Interface at a time (a radio attaches to only one network
// at a time). There is no notion of "modify" (to change settings you tear down
// and re-activate) and Patch does not make semantic sense either, but for the
// convenience of testing (mocks, etc.) all CRUD operations are defined. The
// real service implementation returns unimplemented for Patch.
//
// This message holds only the connection's *identity* (which interface/profile
// combination it is). Real-time information such as connection progress or the
// assigned IP keeps changing, so it is not stored as entity fields; instead it
// is delivered via the ConnectionStatus returned by
// ConnectionService.Watch/GetStatus (see connection_svc.ext.proto).
type Connection struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Interface   *Interface             `protobuf:"bytes,8,opt,name=interface"`
	xxx_hidden_Profile     *Profile               `protobuf:"bytes,9,opt,name=profile"`
	xxx_hidden_AccessPoint *AccessPoint           `protobuf:"bytes,10,opt,name=access_point,json=accessPoint"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_wifi_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Connection) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Connection) GetInterface() *Interface {
	if x != nil {
		return x.xxx_hidden_Interface
	}
	return nil
}

func (x *Connection) GetProfile() *Profile {
	if x != nil {
		return x.xxx_hidden_Profile
	}
	return nil
}

func (x *Connection) GetAccessPoint() *AccessPoint {
	if x != nil {
		return x.xxx_hidden_AccessPoint
	}
	return nil
}

func (x *Connection) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Connection) SetInterface(v *Interface) {
	x.xxx_hidden_Interface = v
}

func (x *Connection) SetProfile(v *Profile) {
	x.xxx_hidden_Profile = v
}

func (x *Connection) SetAccessPoint(v *AccessPoint) {
	x.xxx_hidden_AccessPoint = v
}

func (x *Connection) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Connection) HasInterface() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Interface != nil
}

func (x *Connection) HasProfile() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Profile != nil
}

func (x *Connection) HasAccessPoint() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessPoint != nil
}

func (x *Connection) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Connection) ClearInterface() {
	x.xxx_hidden_Interface = nil
}

func (x *Connection) ClearProfile() {
	x.xxx_hidden_Profile = nil
}

func (x *Connection) ClearAccessPoint() {
	x.xxx_hidden_AccessPoint = nil
}

type Connection_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Connection identifier (auto-generated UUID).
	Id []byte
	// The wireless interface this connection uses. Cannot be changed after activation.
	Interface *Interface
	// The profile applied to this connection (credentials/IP settings, etc.). Cannot be changed.
	Profile *Profile
	// Set this when you want to pin the connection to a specific AP (BSS). If not
	// set, the system selects an appropriate AP among those with the same SSID
	// (including roaming).
	AccessPoint *AccessPoint
}

func (b0 Connection_builder) Build() *Connection {
	m0 := &Connection{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Interface = b.Interface
	x.xxx_hidden_Profile = b.Profile
	x.xxx_hidden_AccessPoint = b.AccessPoint
	return m0
}

var File_wifi_connection_proto protoreflect.FileDescriptor

const file_wifi_connection_proto_rawDesc = "" +
	"\n" +
	"\x15wifi/connection.proto\x12\x04wifi\x1a\torm.proto\x1a\x17wifi/access_point.proto\x1a\x14wifi/interface.proto\x1a\x12wifi/profile.proto\"\xdb\x01\n" +
	"\n" +
	"Connection\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x125\n" +
	"\tinterface\x18\b \x01(\v2\x0f.wifi.InterfaceB\x06\xf2\x82\x16\x02@\x01R\tinterface\x12/\n" +
	"\aprofile\x18\t \x01(\v2\r.wifi.ProfileB\x06\xf2\x82\x16\x02@\x01R\aprofile\x12>\n" +
	"\faccess_point\x18\n" +
	" \x01(\v2\x11.wifi.AccessPointB\b\xf2\x82\x16\x048\x01@\x01R\vaccessPoint:\b\xca\xfc\x15\x04\x12\x02\x10\x01B'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wifi_connection_proto_goTypes = []any{
	(*Connection)(nil),  // 0: wifi.Connection
	(*Interface)(nil),   // 1: wifi.Interface
	(*Profile)(nil),     // 2: wifi.Profile
	(*AccessPoint)(nil), // 3: wifi.AccessPoint
}
var file_wifi_connection_proto_depIdxs = []int32{
	1, // 0: wifi.Connection.interface:type_name -> wifi.Interface
	2, // 1: wifi.Connection.profile:type_name -> wifi.Profile
	3, // 2: wifi.Connection.access_point:type_name -> wifi.AccessPoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wifi_connection_proto_init() }
func file_wifi_connection_proto_init() {
	if File_wifi_connection_proto != nil {
		return
	}
	file_wifi_access_point_proto_init()
	file_wifi_interface_proto_init()
	file_wifi_profile_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_connection_proto_rawDesc), len(file_wifi_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_connection_proto_goTypes,
		DependencyIndexes: file_wifi_connection_proto_depIdxs,
		MessageInfos:      file_wifi_connection_proto_msgTypes,
	}.Build()
	File_wifi_connection_proto = out.File
	file_wifi_connection_proto_goTypes = nil
	file_wifi_connection_proto_depIdxs = nil
}
