// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/interface.proto

package wifi

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Interface represents a single wireless network interface (radio) on a remote
// node. e.g. wlan0. A node may have more than one.
//
// An interface is a target that is *discovered* from the hardware, so having a
// client create or delete it directly does not make semantic sense. However,
// for the convenience of testing (mocks, etc.) all CRUD operations are defined,
// and the real service implementation returns unimplemented for
// Add/Patch/Erase. Listing and power control (on/off) are added as separate
// RPCs in the InterfaceService extension (interface_svc.ext.proto).
type Interface struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        *string                `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Mac         *string                `protobuf:"bytes,7,opt,name=mac"`
	xxx_hidden_Powered     bool                   `protobuf:"varint,8,opt,name=powered"`
	xxx_hidden_Up          bool                   `protobuf:"varint,9,opt,name=up"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_wifi_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Interface) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Interface) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Interface) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *Interface) GetMac() string {
	if x != nil {
		if x.xxx_hidden_Mac != nil {
			return *x.xxx_hidden_Mac
		}
		return ""
	}
	return ""
}

func (x *Interface) GetPowered() bool {
	if x != nil {
		return x.xxx_hidden_Powered
	}
	return false
}

func (x *Interface) GetUp() bool {
	if x != nil {
		return x.xxx_hidden_Up
	}
	return false
}

func (x *Interface) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Interface) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *Interface) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *Interface) SetMac(v string) {
	x.xxx_hidden_Mac = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Interface) SetPowered(v bool) {
	x.xxx_hidden_Powered = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Interface) SetUp(v bool) {
	x.xxx_hidden_Up = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *Interface) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Interface) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Interface) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Interface) HasMac() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Interface) HasPowered() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Interface) HasUp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Interface) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Interface) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Interface) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Desc = nil
}

func (x *Interface) ClearMac() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Mac = nil
}

func (x *Interface) ClearPowered() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Powered = false
}

func (x *Interface) ClearUp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Up = false
}

type Interface_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Interface identifier. Depending on the implementation, the ifname
	// (e.g. "wlan0") may be used directly.
	Id *string
	// Human-readable name.
	Name *string
	// Description.
	Desc *string
	// Hardware (MAC) address.
	Mac *string
	// Radio power state (rfkill, etc.). If true, it is on and scanning/connecting
	// is possible. Reported by the system; use InterfaceService.SetPower to change
	// the value.
	Powered *bool
	// Whether the link is up (active). A read-only state reported by the system.
	Up *bool
}

func (b0 Interface_builder) Build() *Interface {
	m0 := &Interface{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Desc = b.Desc
	}
	if b.Mac != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Mac = b.Mac
	}
	if b.Powered != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Powered = *b.Powered
	}
	if b.Up != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Up = *b.Up
	}
	return m0
}

var File_wifi_interface_proto protoreflect.FileDescriptor

const file_wifi_interface_proto_rawDesc = "" +
	"\n" +
	"\x14wifi/interface.proto\x12\x04wifi\x1a\torm.proto\"\xc1\x01\n" +
	"\tInterface\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xea\x82\x16\x05(\x01\x82\x01\x00R\x02id\x12\x1b\n" +
	"\x04name\x18\x05 \x01(\tB\a\xea\x82\x16\x03\x82\x01\x00R\x04name\x12\x1b\n" +
	"\x04desc\x18\x06 \x01(\tB\a\xea\x82\x16\x03\x82\x01\x00R\x04desc\x12\x19\n" +
	"\x03mac\x18\a \x01(\tB\a\xea\x82\x16\x03\x82\x01\x00R\x03mac\x12!\n" +
	"\apowered\x18\b \x01(\bB\a\xea\x82\x16\x03\x82\x01\x00R\apowered\x12\x17\n" +
	"\x02up\x18\t \x01(\bB\a\xea\x82\x16\x03\x82\x01\x00R\x02up:\b\xca\xfc\x15\x04\x12\x02\x10\x01B'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wifi_interface_proto_goTypes = []any{
	(*Interface)(nil), // 0: wifi.Interface
}
var file_wifi_interface_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wifi_interface_proto_init() }
func file_wifi_interface_proto_init() {
	if File_wifi_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_interface_proto_rawDesc), len(file_wifi_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_interface_proto_goTypes,
		DependencyIndexes: file_wifi_interface_proto_depIdxs,
		MessageInfos:      file_wifi_interface_proto_msgTypes,
	}.Build()
	File_wifi_interface_proto = out.File
	file_wifi_interface_proto_goTypes = nil
	file_wifi_interface_proto_depIdxs = nil
}
