// Code generated by protoc-gen-orm-service. DO NOT EDIT.
// source: wifi/interface.proto.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: wifi/interface_svc.g.proto

package wifi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterfaceService_Add_FullMethodName      = "/wifi.InterfaceService/Add"
	InterfaceService_Get_FullMethodName      = "/wifi.InterfaceService/Get"
	InterfaceService_Patch_FullMethodName    = "/wifi.InterfaceService/Patch"
	InterfaceService_Erase_FullMethodName    = "/wifi.InterfaceService/Erase"
	InterfaceService_List_FullMethodName     = "/wifi.InterfaceService/List"
	InterfaceService_SetPower_FullMethodName = "/wifi.InterfaceService/SetPower"
)

// InterfaceServiceClient is the client API for InterfaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterfaceServiceClient interface {
	// Add creates a new Interface
	Add(ctx context.Context, in *InterfaceAddRequest, opts ...grpc.CallOption) (*Interface, error)
	// Get retrieves a Interface
	Get(ctx context.Context, in *InterfaceGetRequest, opts ...grpc.CallOption) (*Interface, error)
	// Patch updates an existing Interface
	Patch(ctx context.Context, in *InterfacePatchRequest, opts ...grpc.CallOption) (*Interface, error)
	// Erase deletes a Interface
	Erase(ctx context.Context, in *InterfaceRef, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// List는 노드의 모든 무선 인터페이스를 열거한다.
	List(ctx context.Context, in *InterfaceListRequest, opts ...grpc.CallOption) (*InterfaceListResponse, error)
	// SetPower는 인터페이스의 라디오 전원을 켜거나 끈다.
	SetPower(ctx context.Context, in *InterfaceSetPowerRequest, opts ...grpc.CallOption) (*Interface, error)
}

type interfaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterfaceServiceClient(cc grpc.ClientConnInterface) InterfaceServiceClient {
	return &interfaceServiceClient{cc}
}

func (c *interfaceServiceClient) Add(ctx context.Context, in *InterfaceAddRequest, opts ...grpc.CallOption) (*Interface, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Interface)
	err := c.cc.Invoke(ctx, InterfaceService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceServiceClient) Get(ctx context.Context, in *InterfaceGetRequest, opts ...grpc.CallOption) (*Interface, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Interface)
	err := c.cc.Invoke(ctx, InterfaceService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceServiceClient) Patch(ctx context.Context, in *InterfacePatchRequest, opts ...grpc.CallOption) (*Interface, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Interface)
	err := c.cc.Invoke(ctx, InterfaceService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceServiceClient) Erase(ctx context.Context, in *InterfaceRef, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, InterfaceService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceServiceClient) List(ctx context.Context, in *InterfaceListRequest, opts ...grpc.CallOption) (*InterfaceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterfaceListResponse)
	err := c.cc.Invoke(ctx, InterfaceService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceServiceClient) SetPower(ctx context.Context, in *InterfaceSetPowerRequest, opts ...grpc.CallOption) (*Interface, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Interface)
	err := c.cc.Invoke(ctx, InterfaceService_SetPower_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterfaceServiceServer is the server API for InterfaceService service.
// All implementations must embed UnimplementedInterfaceServiceServer
// for forward compatibility.
type InterfaceServiceServer interface {
	// Add creates a new Interface
	Add(context.Context, *InterfaceAddRequest) (*Interface, error)
	// Get retrieves a Interface
	Get(context.Context, *InterfaceGetRequest) (*Interface, error)
	// Patch updates an existing Interface
	Patch(context.Context, *InterfacePatchRequest) (*Interface, error)
	// Erase deletes a Interface
	Erase(context.Context, *InterfaceRef) (*emptypb.Empty, error)
	// List는 노드의 모든 무선 인터페이스를 열거한다.
	List(context.Context, *InterfaceListRequest) (*InterfaceListResponse, error)
	// SetPower는 인터페이스의 라디오 전원을 켜거나 끈다.
	SetPower(context.Context, *InterfaceSetPowerRequest) (*Interface, error)
	mustEmbedUnimplementedInterfaceServiceServer()
}

// UnimplementedInterfaceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterfaceServiceServer struct{}

func (UnimplementedInterfaceServiceServer) Add(context.Context, *InterfaceAddRequest) (*Interface, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedInterfaceServiceServer) Get(context.Context, *InterfaceGetRequest) (*Interface, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedInterfaceServiceServer) Patch(context.Context, *InterfacePatchRequest) (*Interface, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedInterfaceServiceServer) Erase(context.Context, *InterfaceRef) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedInterfaceServiceServer) List(context.Context, *InterfaceListRequest) (*InterfaceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedInterfaceServiceServer) SetPower(context.Context, *InterfaceSetPowerRequest) (*Interface, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPower not implemented")
}
func (UnimplementedInterfaceServiceServer) mustEmbedUnimplementedInterfaceServiceServer() {}
func (UnimplementedInterfaceServiceServer) testEmbeddedByValue()                          {}

// UnsafeInterfaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterfaceServiceServer will
// result in compilation errors.
type UnsafeInterfaceServiceServer interface {
	mustEmbedUnimplementedInterfaceServiceServer()
}

func RegisterInterfaceServiceServer(s grpc.ServiceRegistrar, srv InterfaceServiceServer) {
	// If the following call panics, it indicates UnimplementedInterfaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterfaceService_ServiceDesc, srv)
}

func _InterfaceService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterfaceService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServiceServer).Add(ctx, req.(*InterfaceAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterfaceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterfaceService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServiceServer).Get(ctx, req.(*InterfaceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterfaceService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfacePatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterfaceService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServiceServer).Patch(ctx, req.(*InterfacePatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterfaceService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterfaceService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServiceServer).Erase(ctx, req.(*InterfaceRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterfaceService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterfaceService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServiceServer).List(ctx, req.(*InterfaceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterfaceService_SetPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceSetPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceServiceServer).SetPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterfaceService_SetPower_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceServiceServer).SetPower(ctx, req.(*InterfaceSetPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterfaceService_ServiceDesc is the grpc.ServiceDesc for InterfaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterfaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wifi.InterfaceService",
	HandlerType: (*InterfaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _InterfaceService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _InterfaceService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _InterfaceService_Patch_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _InterfaceService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _InterfaceService_List_Handler,
		},
		{
			MethodName: "SetPower",
			Handler:    _InterfaceService_SetPower_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wifi/interface_svc.g.proto",
}
