// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/interface_svc.g.proto

package wifi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterfaceAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        *string                `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Mac         *string                `protobuf:"bytes,7,opt,name=mac"`
	xxx_hidden_Powered     bool                   `protobuf:"varint,8,opt,name=powered"`
	xxx_hidden_Up          bool                   `protobuf:"varint,9,opt,name=up"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InterfaceAddRequest) Reset() {
	*x = InterfaceAddRequest{}
	mi := &file_wifi_interface_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceAddRequest) ProtoMessage() {}

func (x *InterfaceAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_interface_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceAddRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *InterfaceAddRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *InterfaceAddRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *InterfaceAddRequest) GetMac() string {
	if x != nil {
		if x.xxx_hidden_Mac != nil {
			return *x.xxx_hidden_Mac
		}
		return ""
	}
	return ""
}

func (x *InterfaceAddRequest) GetPowered() bool {
	if x != nil {
		return x.xxx_hidden_Powered
	}
	return false
}

func (x *InterfaceAddRequest) GetUp() bool {
	if x != nil {
		return x.xxx_hidden_Up
	}
	return false
}

func (x *InterfaceAddRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *InterfaceAddRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *InterfaceAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *InterfaceAddRequest) SetMac(v string) {
	x.xxx_hidden_Mac = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *InterfaceAddRequest) SetPowered(v bool) {
	x.xxx_hidden_Powered = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *InterfaceAddRequest) SetUp(v bool) {
	x.xxx_hidden_Up = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *InterfaceAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InterfaceAddRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InterfaceAddRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *InterfaceAddRequest) HasMac() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *InterfaceAddRequest) HasPowered() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *InterfaceAddRequest) HasUp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *InterfaceAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *InterfaceAddRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *InterfaceAddRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Desc = nil
}

func (x *InterfaceAddRequest) ClearMac() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Mac = nil
}

func (x *InterfaceAddRequest) ClearPowered() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Powered = false
}

func (x *InterfaceAddRequest) ClearUp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Up = false
}

type InterfaceAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Name    *string
	Desc    *string
	Mac     *string
	Powered *bool
	Up      *bool
}

func (b0 InterfaceAddRequest_builder) Build() *InterfaceAddRequest {
	m0 := &InterfaceAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Desc = b.Desc
	}
	if b.Mac != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Mac = b.Mac
	}
	if b.Powered != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Powered = *b.Powered
	}
	if b.Up != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Up = *b.Up
	}
	return m0
}

type InterfaceGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *InterfaceRef          `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *InterfaceSelect       `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InterfaceGetRequest) Reset() {
	*x = InterfaceGetRequest{}
	mi := &file_wifi_interface_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceGetRequest) ProtoMessage() {}

func (x *InterfaceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_interface_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceGetRequest) GetRef() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *InterfaceGetRequest) GetSelect() *InterfaceSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *InterfaceGetRequest) SetRef(v *InterfaceRef) {
	x.xxx_hidden_Ref = v
}

func (x *InterfaceGetRequest) SetSelect(v *InterfaceSelect) {
	x.xxx_hidden_Select = v
}

func (x *InterfaceGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *InterfaceGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *InterfaceGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *InterfaceGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type InterfaceGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *InterfaceRef
	Select *InterfaceSelect
}

func (b0 InterfaceGetRequest_builder) Build() *InterfaceGetRequest {
	m0 := &InterfaceGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type InterfaceRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isInterfaceRef_Key     `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterfaceRef) Reset() {
	*x = InterfaceRef{}
	mi := &file_wifi_interface_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceRef) ProtoMessage() {}

func (x *InterfaceRef) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_interface_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceRef) GetId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*interfaceRef_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *InterfaceRef) SetId(v string) {
	x.xxx_hidden_Key = &interfaceRef_Id{v}
}

func (x *InterfaceRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *InterfaceRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*interfaceRef_Id)
	return ok
}

func (x *InterfaceRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *InterfaceRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*interfaceRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

const InterfaceRef_Key_not_set_case case_InterfaceRef_Key = 0
const InterfaceRef_Id_case case_InterfaceRef_Key = 1

func (x *InterfaceRef) WhichKey() case_InterfaceRef_Key {
	if x == nil {
		return InterfaceRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *interfaceRef_Id:
		return InterfaceRef_Id_case
	default:
		return InterfaceRef_Key_not_set_case
	}
}

type InterfaceRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id *string
	// -- end of xxx_hidden_Key
}

func (b0 InterfaceRef_builder) Build() *InterfaceRef {
	m0 := &InterfaceRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &interfaceRef_Id{*b.Id}
	}
	return m0
}

type case_InterfaceRef_Key protoreflect.FieldNumber

func (x case_InterfaceRef_Key) String() string {
	md := file_wifi_interface_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isInterfaceRef_Key interface {
	isInterfaceRef_Key()
}

type interfaceRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,oneof"`
}

func (*interfaceRef_Id) isInterfaceRef_Key() {}

type InterfaceSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Name        bool                   `protobuf:"varint,5,opt,name=name"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,6,opt,name=desc"`
	xxx_hidden_Mac         bool                   `protobuf:"varint,7,opt,name=mac"`
	xxx_hidden_Powered     bool                   `protobuf:"varint,8,opt,name=powered"`
	xxx_hidden_Up          bool                   `protobuf:"varint,9,opt,name=up"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InterfaceSelect) Reset() {
	*x = InterfaceSelect{}
	mi := &file_wifi_interface_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceSelect) ProtoMessage() {}

func (x *InterfaceSelect) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_interface_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *InterfaceSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *InterfaceSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *InterfaceSelect) GetMac() bool {
	if x != nil {
		return x.xxx_hidden_Mac
	}
	return false
}

func (x *InterfaceSelect) GetPowered() bool {
	if x != nil {
		return x.xxx_hidden_Powered
	}
	return false
}

func (x *InterfaceSelect) GetUp() bool {
	if x != nil {
		return x.xxx_hidden_Up
	}
	return false
}

func (x *InterfaceSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *InterfaceSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *InterfaceSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *InterfaceSelect) SetMac(v bool) {
	x.xxx_hidden_Mac = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *InterfaceSelect) SetPowered(v bool) {
	x.xxx_hidden_Powered = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *InterfaceSelect) SetUp(v bool) {
	x.xxx_hidden_Up = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *InterfaceSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InterfaceSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InterfaceSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *InterfaceSelect) HasMac() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *InterfaceSelect) HasPowered() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *InterfaceSelect) HasUp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *InterfaceSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *InterfaceSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = false
}

func (x *InterfaceSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Desc = false
}

func (x *InterfaceSelect) ClearMac() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Mac = false
}

func (x *InterfaceSelect) ClearPowered() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Powered = false
}

func (x *InterfaceSelect) ClearUp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Up = false
}

type InterfaceSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All     *bool
	Name    *bool
	Desc    *bool
	Mac     *bool
	Powered *bool
	Up      *bool
}

func (b0 InterfaceSelect_builder) Build() *InterfaceSelect {
	m0 := &InterfaceSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_All = *b.All
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Mac != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Mac = *b.Mac
	}
	if b.Powered != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Powered = *b.Powered
	}
	if b.Up != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Up = *b.Up
	}
	return m0
}

type InterfacePatchRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *InterfaceRef          `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Name        *string                `protobuf:"bytes,9,opt,name=name"`
	xxx_hidden_NameNull    bool                   `protobuf:"varint,10,opt,name=name_null,json=nameNull"`
	xxx_hidden_Desc        *string                `protobuf:"bytes,11,opt,name=desc"`
	xxx_hidden_DescNull    bool                   `protobuf:"varint,12,opt,name=desc_null,json=descNull"`
	xxx_hidden_Mac         *string                `protobuf:"bytes,13,opt,name=mac"`
	xxx_hidden_MacNull     bool                   `protobuf:"varint,14,opt,name=mac_null,json=macNull"`
	xxx_hidden_Powered     bool                   `protobuf:"varint,15,opt,name=powered"`
	xxx_hidden_PoweredNull bool                   `protobuf:"varint,16,opt,name=powered_null,json=poweredNull"`
	xxx_hidden_Up          bool                   `protobuf:"varint,17,opt,name=up"`
	xxx_hidden_UpNull      bool                   `protobuf:"varint,18,opt,name=up_null,json=upNull"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InterfacePatchRequest) Reset() {
	*x = InterfacePatchRequest{}
	mi := &file_wifi_interface_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfacePatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacePatchRequest) ProtoMessage() {}

func (x *InterfacePatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_interface_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfacePatchRequest) GetRef() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *InterfacePatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *InterfacePatchRequest) GetNameNull() bool {
	if x != nil {
		return x.xxx_hidden_NameNull
	}
	return false
}

func (x *InterfacePatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *InterfacePatchRequest) GetDescNull() bool {
	if x != nil {
		return x.xxx_hidden_DescNull
	}
	return false
}

func (x *InterfacePatchRequest) GetMac() string {
	if x != nil {
		if x.xxx_hidden_Mac != nil {
			return *x.xxx_hidden_Mac
		}
		return ""
	}
	return ""
}

func (x *InterfacePatchRequest) GetMacNull() bool {
	if x != nil {
		return x.xxx_hidden_MacNull
	}
	return false
}

func (x *InterfacePatchRequest) GetPowered() bool {
	if x != nil {
		return x.xxx_hidden_Powered
	}
	return false
}

func (x *InterfacePatchRequest) GetPoweredNull() bool {
	if x != nil {
		return x.xxx_hidden_PoweredNull
	}
	return false
}

func (x *InterfacePatchRequest) GetUp() bool {
	if x != nil {
		return x.xxx_hidden_Up
	}
	return false
}

func (x *InterfacePatchRequest) GetUpNull() bool {
	if x != nil {
		return x.xxx_hidden_UpNull
	}
	return false
}

func (x *InterfacePatchRequest) SetRef(v *InterfaceRef) {
	x.xxx_hidden_Ref = v
}

func (x *InterfacePatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *InterfacePatchRequest) SetNameNull(v bool) {
	x.xxx_hidden_NameNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *InterfacePatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *InterfacePatchRequest) SetDescNull(v bool) {
	x.xxx_hidden_DescNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *InterfacePatchRequest) SetMac(v string) {
	x.xxx_hidden_Mac = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *InterfacePatchRequest) SetMacNull(v bool) {
	x.xxx_hidden_MacNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 11)
}

func (x *InterfacePatchRequest) SetPowered(v bool) {
	x.xxx_hidden_Powered = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 11)
}

func (x *InterfacePatchRequest) SetPoweredNull(v bool) {
	x.xxx_hidden_PoweredNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 11)
}

func (x *InterfacePatchRequest) SetUp(v bool) {
	x.xxx_hidden_Up = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 11)
}

func (x *InterfacePatchRequest) SetUpNull(v bool) {
	x.xxx_hidden_UpNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *InterfacePatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *InterfacePatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InterfacePatchRequest) HasNameNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *InterfacePatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *InterfacePatchRequest) HasDescNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *InterfacePatchRequest) HasMac() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *InterfacePatchRequest) HasMacNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *InterfacePatchRequest) HasPowered() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *InterfacePatchRequest) HasPoweredNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *InterfacePatchRequest) HasUp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *InterfacePatchRequest) HasUpNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *InterfacePatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *InterfacePatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *InterfacePatchRequest) ClearNameNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_NameNull = false
}

func (x *InterfacePatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = nil
}

func (x *InterfacePatchRequest) ClearDescNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_DescNull = false
}

func (x *InterfacePatchRequest) ClearMac() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Mac = nil
}

func (x *InterfacePatchRequest) ClearMacNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_MacNull = false
}

func (x *InterfacePatchRequest) ClearPowered() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Powered = false
}

func (x *InterfacePatchRequest) ClearPoweredNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_PoweredNull = false
}

func (x *InterfacePatchRequest) ClearUp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Up = false
}

func (x *InterfacePatchRequest) ClearUpNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_UpNull = false
}

type InterfacePatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref         *InterfaceRef
	Name        *string
	NameNull    *bool
	Desc        *string
	DescNull    *bool
	Mac         *string
	MacNull     *bool
	Powered     *bool
	PoweredNull *bool
	Up          *bool
	UpNull      *bool
}

func (b0 InterfacePatchRequest_builder) Build() *InterfacePatchRequest {
	m0 := &InterfacePatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Name = b.Name
	}
	if b.NameNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_NameNull = *b.NameNull
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_Desc = b.Desc
	}
	if b.DescNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_DescNull = *b.DescNull
	}
	if b.Mac != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_Mac = b.Mac
	}
	if b.MacNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 11)
		x.xxx_hidden_MacNull = *b.MacNull
	}
	if b.Powered != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 11)
		x.xxx_hidden_Powered = *b.Powered
	}
	if b.PoweredNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 11)
		x.xxx_hidden_PoweredNull = *b.PoweredNull
	}
	if b.Up != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 11)
		x.xxx_hidden_Up = *b.Up
	}
	if b.UpNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_UpNull = *b.UpNull
	}
	return m0
}

type InterfaceListRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceListRequest) Reset() {
	*x = InterfaceListRequest{}
	mi := &file_wifi_interface_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceListRequest) ProtoMessage() {}

func (x *InterfaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_interface_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type InterfaceListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 InterfaceListRequest_builder) Build() *InterfaceListRequest {
	m0 := &InterfaceListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type InterfaceListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Interface          `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InterfaceListResponse) Reset() {
	*x = InterfaceListResponse{}
	mi := &file_wifi_interface_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceListResponse) ProtoMessage() {}

func (x *InterfaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_interface_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceListResponse) GetItems() []*Interface {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *InterfaceListResponse) SetItems(v []*Interface) {
	x.xxx_hidden_Items = &v
}

type InterfaceListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of interfaces.
	Items []*Interface
}

func (b0 InterfaceListResponse_builder) Build() *InterfaceListResponse {
	m0 := &InterfaceListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type InterfaceSetPowerRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *InterfaceRef          `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_On          bool                   `protobuf:"varint,2,opt,name=on"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InterfaceSetPowerRequest) Reset() {
	*x = InterfaceSetPowerRequest{}
	mi := &file_wifi_interface_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceSetPowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceSetPowerRequest) ProtoMessage() {}

func (x *InterfaceSetPowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_interface_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InterfaceSetPowerRequest) GetRef() *InterfaceRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *InterfaceSetPowerRequest) GetOn() bool {
	if x != nil {
		return x.xxx_hidden_On
	}
	return false
}

func (x *InterfaceSetPowerRequest) SetRef(v *InterfaceRef) {
	x.xxx_hidden_Ref = v
}

func (x *InterfaceSetPowerRequest) SetOn(v bool) {
	x.xxx_hidden_On = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *InterfaceSetPowerRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *InterfaceSetPowerRequest) HasOn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *InterfaceSetPowerRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *InterfaceSetPowerRequest) ClearOn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_On = false
}

type InterfaceSetPowerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The interface whose power to control.
	Ref *InterfaceRef
	// If true, turn the radio on; if false, turn it off.
	On *bool
}

func (b0 InterfaceSetPowerRequest_builder) Build() *InterfaceSetPowerRequest {
	m0 := &InterfaceSetPowerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.On != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_On = *b.On
	}
	return m0
}

var File_wifi_interface_svc_g_proto protoreflect.FileDescriptor

const file_wifi_interface_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x1awifi/interface_svc.g.proto\x12\x04wifi\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14wifi/interface.proto\"\x89\x01\n" +
	"\x13InterfaceAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12\x10\n" +
	"\x03mac\x18\a \x01(\tR\x03mac\x12\x18\n" +
	"\apowered\x18\b \x01(\bR\apowered\x12\x0e\n" +
	"\x02up\x18\t \x01(\bR\x02up\"j\n" +
	"\x13InterfaceGetRequest\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.wifi.InterfaceRefR\x03ref\x12-\n" +
	"\x06select\x18\x02 \x01(\v2\x15.wifi.InterfaceSelectR\x06select\"'\n" +
	"\fInterfaceRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02idB\x05\n" +
	"\x03key\"\x87\x01\n" +
	"\x0fInterfaceSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x12\n" +
	"\x04name\x18\x05 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\bR\x04desc\x12\x10\n" +
	"\x03mac\x18\a \x01(\bR\x03mac\x12\x18\n" +
	"\apowered\x18\b \x01(\bR\apowered\x12\x0e\n" +
	"\x02up\x18\t \x01(\bR\x02up\"\xb2\x02\n" +
	"\x15InterfacePatchRequest\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.wifi.InterfaceRefR\x03ref\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x1b\n" +
	"\tname_null\x18\n" +
	" \x01(\bR\bnameNull\x12\x12\n" +
	"\x04desc\x18\v \x01(\tR\x04desc\x12\x1b\n" +
	"\tdesc_null\x18\f \x01(\bR\bdescNull\x12\x10\n" +
	"\x03mac\x18\r \x01(\tR\x03mac\x12\x19\n" +
	"\bmac_null\x18\x0e \x01(\bR\amacNull\x12\x18\n" +
	"\apowered\x18\x0f \x01(\bR\apowered\x12!\n" +
	"\fpowered_null\x18\x10 \x01(\bR\vpoweredNull\x12\x0e\n" +
	"\x02up\x18\x11 \x01(\bR\x02up\x12\x17\n" +
	"\aup_null\x18\x12 \x01(\bR\x06upNull\"\x16\n" +
	"\x14InterfaceListRequest\">\n" +
	"\x15InterfaceListResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.wifi.InterfaceR\x05items\"P\n" +
	"\x18InterfaceSetPowerRequest\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.wifi.InterfaceRefR\x03ref\x12\x0e\n" +
	"\x02on\x18\x02 \x01(\bR\x02on2\xe2\x02\n" +
	"\x10InterfaceService\x121\n" +
	"\x03Add\x12\x19.wifi.InterfaceAddRequest\x1a\x0f.wifi.Interface\x121\n" +
	"\x03Get\x12\x19.wifi.InterfaceGetRequest\x1a\x0f.wifi.Interface\x125\n" +
	"\x05Patch\x12\x1b.wifi.InterfacePatchRequest\x1a\x0f.wifi.Interface\x123\n" +
	"\x05Erase\x12\x12.wifi.InterfaceRef\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x04List\x12\x1a.wifi.InterfaceListRequest\x1a\x1b.wifi.InterfaceListResponse\x12;\n" +
	"\bSetPower\x12\x1e.wifi.InterfaceSetPowerRequest\x1a\x0f.wifi.InterfaceB'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_interface_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wifi_interface_svc_g_proto_goTypes = []any{
	(*InterfaceAddRequest)(nil),      // 0: wifi.InterfaceAddRequest
	(*InterfaceGetRequest)(nil),      // 1: wifi.InterfaceGetRequest
	(*InterfaceRef)(nil),             // 2: wifi.InterfaceRef
	(*InterfaceSelect)(nil),          // 3: wifi.InterfaceSelect
	(*InterfacePatchRequest)(nil),    // 4: wifi.InterfacePatchRequest
	(*InterfaceListRequest)(nil),     // 5: wifi.InterfaceListRequest
	(*InterfaceListResponse)(nil),    // 6: wifi.InterfaceListResponse
	(*InterfaceSetPowerRequest)(nil), // 7: wifi.InterfaceSetPowerRequest
	(*Interface)(nil),                // 8: wifi.Interface
	(*emptypb.Empty)(nil),            // 9: google.protobuf.Empty
}
var file_wifi_interface_svc_g_proto_depIdxs = []int32{
	2,  // 0: wifi.InterfaceGetRequest.ref:type_name -> wifi.InterfaceRef
	3,  // 1: wifi.InterfaceGetRequest.select:type_name -> wifi.InterfaceSelect
	2,  // 2: wifi.InterfacePatchRequest.ref:type_name -> wifi.InterfaceRef
	8,  // 3: wifi.InterfaceListResponse.items:type_name -> wifi.Interface
	2,  // 4: wifi.InterfaceSetPowerRequest.ref:type_name -> wifi.InterfaceRef
	0,  // 5: wifi.InterfaceService.Add:input_type -> wifi.InterfaceAddRequest
	1,  // 6: wifi.InterfaceService.Get:input_type -> wifi.InterfaceGetRequest
	4,  // 7: wifi.InterfaceService.Patch:input_type -> wifi.InterfacePatchRequest
	2,  // 8: wifi.InterfaceService.Erase:input_type -> wifi.InterfaceRef
	5,  // 9: wifi.InterfaceService.List:input_type -> wifi.InterfaceListRequest
	7,  // 10: wifi.InterfaceService.SetPower:input_type -> wifi.InterfaceSetPowerRequest
	8,  // 11: wifi.InterfaceService.Add:output_type -> wifi.Interface
	8,  // 12: wifi.InterfaceService.Get:output_type -> wifi.Interface
	8,  // 13: wifi.InterfaceService.Patch:output_type -> wifi.Interface
	9,  // 14: wifi.InterfaceService.Erase:output_type -> google.protobuf.Empty
	6,  // 15: wifi.InterfaceService.List:output_type -> wifi.InterfaceListResponse
	8,  // 16: wifi.InterfaceService.SetPower:output_type -> wifi.Interface
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_wifi_interface_svc_g_proto_init() }
func file_wifi_interface_svc_g_proto_init() {
	if File_wifi_interface_svc_g_proto != nil {
		return
	}
	file_wifi_interface_proto_init()
	file_wifi_interface_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*interfaceRef_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_interface_svc_g_proto_rawDesc), len(file_wifi_interface_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wifi_interface_svc_g_proto_goTypes,
		DependencyIndexes: file_wifi_interface_svc_g_proto_depIdxs,
		MessageInfos:      file_wifi_interface_svc_g_proto_msgTypes,
	}.Build()
	File_wifi_interface_svc_g_proto = out.File
	file_wifi_interface_svc_g_proto_goTypes = nil
	file_wifi_interface_svc_g_proto_depIdxs = nil
}
