// Code generated by protoc-gen-orm-service. DO NOT EDIT.
// source: wifi/profile.proto.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/profile_svc.g.proto

package wifi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        *string                `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Ssid        *string                `protobuf:"bytes,7,opt,name=ssid"`
	xxx_hidden_Hidden      bool                   `protobuf:"varint,8,opt,name=hidden"`
	xxx_hidden_Autoconnect bool                   `protobuf:"varint,9,opt,name=autoconnect"`
	xxx_hidden_Security    *Security              `protobuf:"bytes,10,opt,name=security"`
	xxx_hidden_Ipv4        *IpConfig              `protobuf:"bytes,11,opt,name=ipv4"`
	xxx_hidden_Ipv6        *IpConfig              `protobuf:"bytes,12,opt,name=ipv6"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileAddRequest) Reset() {
	*x = ProfileAddRequest{}
	mi := &file_wifi_profile_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileAddRequest) ProtoMessage() {}

func (x *ProfileAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_profile_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *ProfileAddRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ProfileAddRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *ProfileAddRequest) GetSsid() string {
	if x != nil {
		if x.xxx_hidden_Ssid != nil {
			return *x.xxx_hidden_Ssid
		}
		return ""
	}
	return ""
}

func (x *ProfileAddRequest) GetHidden() bool {
	if x != nil {
		return x.xxx_hidden_Hidden
	}
	return false
}

func (x *ProfileAddRequest) GetAutoconnect() bool {
	if x != nil {
		return x.xxx_hidden_Autoconnect
	}
	return false
}

func (x *ProfileAddRequest) GetSecurity() *Security {
	if x != nil {
		return x.xxx_hidden_Security
	}
	return nil
}

func (x *ProfileAddRequest) GetIpv4() *IpConfig {
	if x != nil {
		return x.xxx_hidden_Ipv4
	}
	return nil
}

func (x *ProfileAddRequest) GetIpv6() *IpConfig {
	if x != nil {
		return x.xxx_hidden_Ipv6
	}
	return nil
}

func (x *ProfileAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *ProfileAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *ProfileAddRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *ProfileAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *ProfileAddRequest) SetSsid(v string) {
	x.xxx_hidden_Ssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *ProfileAddRequest) SetHidden(v bool) {
	x.xxx_hidden_Hidden = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *ProfileAddRequest) SetAutoconnect(v bool) {
	x.xxx_hidden_Autoconnect = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *ProfileAddRequest) SetSecurity(v *Security) {
	x.xxx_hidden_Security = v
}

func (x *ProfileAddRequest) SetIpv4(v *IpConfig) {
	x.xxx_hidden_Ipv4 = v
}

func (x *ProfileAddRequest) SetIpv6(v *IpConfig) {
	x.xxx_hidden_Ipv6 = v
}

func (x *ProfileAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *ProfileAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileAddRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProfileAddRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProfileAddRequest) HasSsid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ProfileAddRequest) HasHidden() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ProfileAddRequest) HasAutoconnect() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ProfileAddRequest) HasSecurity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Security != nil
}

func (x *ProfileAddRequest) HasIpv4() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ipv4 != nil
}

func (x *ProfileAddRequest) HasIpv6() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ipv6 != nil
}

func (x *ProfileAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *ProfileAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ProfileAddRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *ProfileAddRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Desc = nil
}

func (x *ProfileAddRequest) ClearSsid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Ssid = nil
}

func (x *ProfileAddRequest) ClearHidden() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Hidden = false
}

func (x *ProfileAddRequest) ClearAutoconnect() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Autoconnect = false
}

func (x *ProfileAddRequest) ClearSecurity() {
	x.xxx_hidden_Security = nil
}

func (x *ProfileAddRequest) ClearIpv4() {
	x.xxx_hidden_Ipv4 = nil
}

func (x *ProfileAddRequest) ClearIpv6() {
	x.xxx_hidden_Ipv6 = nil
}

func (x *ProfileAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type ProfileAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Name        *string
	Desc        *string
	Ssid        *string
	Hidden      *bool
	Autoconnect *bool
	Security    *Security
	Ipv4        *IpConfig
	Ipv6        *IpConfig
	DateCreated *timestamppb.Timestamp
}

func (b0 ProfileAddRequest_builder) Build() *ProfileAddRequest {
	m0 := &ProfileAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_Desc = b.Desc
	}
	if b.Ssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_Ssid = b.Ssid
	}
	if b.Hidden != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_Hidden = *b.Hidden
	}
	if b.Autoconnect != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_Autoconnect = *b.Autoconnect
	}
	x.xxx_hidden_Security = b.Security
	x.xxx_hidden_Ipv4 = b.Ipv4
	x.xxx_hidden_Ipv6 = b.Ipv6
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type ProfileRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isProfileRef_Key       `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileRef) Reset() {
	*x = ProfileRef{}
	mi := &file_wifi_profile_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRef) ProtoMessage() {}

func (x *ProfileRef) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_profile_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*profileRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *ProfileRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &profileRef_Id{v}
}

func (x *ProfileRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *ProfileRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*profileRef_Id)
	return ok
}

func (x *ProfileRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *ProfileRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*profileRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

const ProfileRef_Key_not_set_case case_ProfileRef_Key = 0
const ProfileRef_Id_case case_ProfileRef_Key = 1

func (x *ProfileRef) WhichKey() case_ProfileRef_Key {
	if x == nil {
		return ProfileRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *profileRef_Id:
		return ProfileRef_Id_case
	default:
		return ProfileRef_Key_not_set_case
	}
}

type ProfileRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id []byte
	// -- end of xxx_hidden_Key
}

func (b0 ProfileRef_builder) Build() *ProfileRef {
	m0 := &ProfileRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &profileRef_Id{b.Id}
	}
	return m0
}

type case_ProfileRef_Key protoreflect.FieldNumber

func (x case_ProfileRef_Key) String() string {
	md := file_wifi_profile_svc_g_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isProfileRef_Key interface {
	isProfileRef_Key()
}

type profileRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

func (*profileRef_Id) isProfileRef_Key() {}

type ProfileSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Name        bool                   `protobuf:"varint,5,opt,name=name"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,6,opt,name=desc"`
	xxx_hidden_Ssid        bool                   `protobuf:"varint,7,opt,name=ssid"`
	xxx_hidden_Hidden      bool                   `protobuf:"varint,8,opt,name=hidden"`
	xxx_hidden_Autoconnect bool                   `protobuf:"varint,9,opt,name=autoconnect"`
	xxx_hidden_Security    bool                   `protobuf:"varint,10,opt,name=security"`
	xxx_hidden_Ipv4        bool                   `protobuf:"varint,11,opt,name=ipv4"`
	xxx_hidden_Ipv6        bool                   `protobuf:"varint,12,opt,name=ipv6"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileSelect) Reset() {
	*x = ProfileSelect{}
	mi := &file_wifi_profile_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSelect) ProtoMessage() {}

func (x *ProfileSelect) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_profile_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *ProfileSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *ProfileSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *ProfileSelect) GetSsid() bool {
	if x != nil {
		return x.xxx_hidden_Ssid
	}
	return false
}

func (x *ProfileSelect) GetHidden() bool {
	if x != nil {
		return x.xxx_hidden_Hidden
	}
	return false
}

func (x *ProfileSelect) GetAutoconnect() bool {
	if x != nil {
		return x.xxx_hidden_Autoconnect
	}
	return false
}

func (x *ProfileSelect) GetSecurity() bool {
	if x != nil {
		return x.xxx_hidden_Security
	}
	return false
}

func (x *ProfileSelect) GetIpv4() bool {
	if x != nil {
		return x.xxx_hidden_Ipv4
	}
	return false
}

func (x *ProfileSelect) GetIpv6() bool {
	if x != nil {
		return x.xxx_hidden_Ipv6
	}
	return false
}

func (x *ProfileSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *ProfileSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *ProfileSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *ProfileSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *ProfileSelect) SetSsid(v bool) {
	x.xxx_hidden_Ssid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *ProfileSelect) SetHidden(v bool) {
	x.xxx_hidden_Hidden = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *ProfileSelect) SetAutoconnect(v bool) {
	x.xxx_hidden_Autoconnect = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *ProfileSelect) SetSecurity(v bool) {
	x.xxx_hidden_Security = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *ProfileSelect) SetIpv4(v bool) {
	x.xxx_hidden_Ipv4 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *ProfileSelect) SetIpv6(v bool) {
	x.xxx_hidden_Ipv6 = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 10)
}

func (x *ProfileSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *ProfileSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProfileSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProfileSelect) HasSsid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ProfileSelect) HasHidden() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ProfileSelect) HasAutoconnect() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ProfileSelect) HasSecurity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ProfileSelect) HasIpv4() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ProfileSelect) HasIpv6() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ProfileSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ProfileSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *ProfileSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = false
}

func (x *ProfileSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Desc = false
}

func (x *ProfileSelect) ClearSsid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Ssid = false
}

func (x *ProfileSelect) ClearHidden() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Hidden = false
}

func (x *ProfileSelect) ClearAutoconnect() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Autoconnect = false
}

func (x *ProfileSelect) ClearSecurity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Security = false
}

func (x *ProfileSelect) ClearIpv4() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Ipv4 = false
}

func (x *ProfileSelect) ClearIpv6() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Ipv6 = false
}

func (x *ProfileSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DateCreated = false
}

type ProfileSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Name        *bool
	Desc        *bool
	Ssid        *bool
	Hidden      *bool
	Autoconnect *bool
	Security    *bool
	Ipv4        *bool
	Ipv6        *bool
	DateCreated *bool
}

func (b0 ProfileSelect_builder) Build() *ProfileSelect {
	m0 := &ProfileSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_All = *b.All
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Ssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_Ssid = *b.Ssid
	}
	if b.Hidden != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_Hidden = *b.Hidden
	}
	if b.Autoconnect != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_Autoconnect = *b.Autoconnect
	}
	if b.Security != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_Security = *b.Security
	}
	if b.Ipv4 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_Ipv4 = *b.Ipv4
	}
	if b.Ipv6 != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 10)
		x.xxx_hidden_Ipv6 = *b.Ipv6
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type ProfileGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *ProfileRef            `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *ProfileSelect         `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProfileGetRequest) Reset() {
	*x = ProfileGetRequest{}
	mi := &file_wifi_profile_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileGetRequest) ProtoMessage() {}

func (x *ProfileGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_profile_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileGetRequest) GetRef() *ProfileRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ProfileGetRequest) GetSelect() *ProfileSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *ProfileGetRequest) SetRef(v *ProfileRef) {
	x.xxx_hidden_Ref = v
}

func (x *ProfileGetRequest) SetSelect(v *ProfileSelect) {
	x.xxx_hidden_Select = v
}

func (x *ProfileGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ProfileGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *ProfileGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ProfileGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type ProfileGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *ProfileRef
	Select *ProfileSelect
}

func (b0 ProfileGetRequest_builder) Build() *ProfileGetRequest {
	m0 := &ProfileGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type ProfilePatchRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref             *ProfileRef            `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Name            *string                `protobuf:"bytes,9,opt,name=name"`
	xxx_hidden_NameNull        bool                   `protobuf:"varint,10,opt,name=name_null,json=nameNull"`
	xxx_hidden_Desc            *string                `protobuf:"bytes,11,opt,name=desc"`
	xxx_hidden_DescNull        bool                   `protobuf:"varint,12,opt,name=desc_null,json=descNull"`
	xxx_hidden_Ssid            *string                `protobuf:"bytes,13,opt,name=ssid"`
	xxx_hidden_SsidNull        bool                   `protobuf:"varint,14,opt,name=ssid_null,json=ssidNull"`
	xxx_hidden_Hidden          bool                   `protobuf:"varint,15,opt,name=hidden"`
	xxx_hidden_HiddenNull      bool                   `protobuf:"varint,16,opt,name=hidden_null,json=hiddenNull"`
	xxx_hidden_Autoconnect     bool                   `protobuf:"varint,17,opt,name=autoconnect"`
	xxx_hidden_AutoconnectNull bool                   `protobuf:"varint,18,opt,name=autoconnect_null,json=autoconnectNull"`
	xxx_hidden_Security        *Security              `protobuf:"bytes,19,opt,name=security"`
	xxx_hidden_SecurityNull    bool                   `protobuf:"varint,20,opt,name=security_null,json=securityNull"`
	xxx_hidden_Ipv4            *IpConfig              `protobuf:"bytes,21,opt,name=ipv4"`
	xxx_hidden_Ipv4Null        bool                   `protobuf:"varint,22,opt,name=ipv4_null,json=ipv4Null"`
	xxx_hidden_Ipv6            *IpConfig              `protobuf:"bytes,23,opt,name=ipv6"`
	xxx_hidden_Ipv6Null        bool                   `protobuf:"varint,24,opt,name=ipv6_null,json=ipv6Null"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ProfilePatchRequest) Reset() {
	*x = ProfilePatchRequest{}
	mi := &file_wifi_profile_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilePatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePatchRequest) ProtoMessage() {}

func (x *ProfilePatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_profile_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfilePatchRequest) GetRef() *ProfileRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ProfilePatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ProfilePatchRequest) GetNameNull() bool {
	if x != nil {
		return x.xxx_hidden_NameNull
	}
	return false
}

func (x *ProfilePatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *ProfilePatchRequest) GetDescNull() bool {
	if x != nil {
		return x.xxx_hidden_DescNull
	}
	return false
}

func (x *ProfilePatchRequest) GetSsid() string {
	if x != nil {
		if x.xxx_hidden_Ssid != nil {
			return *x.xxx_hidden_Ssid
		}
		return ""
	}
	return ""
}

func (x *ProfilePatchRequest) GetSsidNull() bool {
	if x != nil {
		return x.xxx_hidden_SsidNull
	}
	return false
}

func (x *ProfilePatchRequest) GetHidden() bool {
	if x != nil {
		return x.xxx_hidden_Hidden
	}
	return false
}

func (x *ProfilePatchRequest) GetHiddenNull() bool {
	if x != nil {
		return x.xxx_hidden_HiddenNull
	}
	return false
}

func (x *ProfilePatchRequest) GetAutoconnect() bool {
	if x != nil {
		return x.xxx_hidden_Autoconnect
	}
	return false
}

func (x *ProfilePatchRequest) GetAutoconnectNull() bool {
	if x != nil {
		return x.xxx_hidden_AutoconnectNull
	}
	return false
}

func (x *ProfilePatchRequest) GetSecurity() *Security {
	if x != nil {
		return x.xxx_hidden_Security
	}
	return nil
}

func (x *ProfilePatchRequest) GetSecurityNull() bool {
	if x != nil {
		return x.xxx_hidden_SecurityNull
	}
	return false
}

func (x *ProfilePatchRequest) GetIpv4() *IpConfig {
	if x != nil {
		return x.xxx_hidden_Ipv4
	}
	return nil
}

func (x *ProfilePatchRequest) GetIpv4Null() bool {
	if x != nil {
		return x.xxx_hidden_Ipv4Null
	}
	return false
}

func (x *ProfilePatchRequest) GetIpv6() *IpConfig {
	if x != nil {
		return x.xxx_hidden_Ipv6
	}
	return nil
}

func (x *ProfilePatchRequest) GetIpv6Null() bool {
	if x != nil {
		return x.xxx_hidden_Ipv6Null
	}
	return false
}

func (x *ProfilePatchRequest) SetRef(v *ProfileRef) {
	x.xxx_hidden_Ref = v
}

func (x *ProfilePatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 17)
}

func (x *ProfilePatchRequest) SetNameNull(v bool) {
	x.xxx_hidden_NameNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 17)
}

func (x *ProfilePatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 17)
}

func (x *ProfilePatchRequest) SetDescNull(v bool) {
	x.xxx_hidden_DescNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 17)
}

func (x *ProfilePatchRequest) SetSsid(v string) {
	x.xxx_hidden_Ssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 17)
}

func (x *ProfilePatchRequest) SetSsidNull(v bool) {
	x.xxx_hidden_SsidNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 17)
}

func (x *ProfilePatchRequest) SetHidden(v bool) {
	x.xxx_hidden_Hidden = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 17)
}

func (x *ProfilePatchRequest) SetHiddenNull(v bool) {
	x.xxx_hidden_HiddenNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 17)
}

func (x *ProfilePatchRequest) SetAutoconnect(v bool) {
	x.xxx_hidden_Autoconnect = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 17)
}

func (x *ProfilePatchRequest) SetAutoconnectNull(v bool) {
	x.xxx_hidden_AutoconnectNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 17)
}

func (x *ProfilePatchRequest) SetSecurity(v *Security) {
	x.xxx_hidden_Security = v
}

func (x *ProfilePatchRequest) SetSecurityNull(v bool) {
	x.xxx_hidden_SecurityNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 17)
}

func (x *ProfilePatchRequest) SetIpv4(v *IpConfig) {
	x.xxx_hidden_Ipv4 = v
}

func (x *ProfilePatchRequest) SetIpv4Null(v bool) {
	x.xxx_hidden_Ipv4Null = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 17)
}

func (x *ProfilePatchRequest) SetIpv6(v *IpConfig) {
	x.xxx_hidden_Ipv6 = v
}

func (x *ProfilePatchRequest) SetIpv6Null(v bool) {
	x.xxx_hidden_Ipv6Null = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 16, 17)
}

func (x *ProfilePatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ProfilePatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProfilePatchRequest) HasNameNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProfilePatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ProfilePatchRequest) HasDescNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ProfilePatchRequest) HasSsid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ProfilePatchRequest) HasSsidNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ProfilePatchRequest) HasHidden() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ProfilePatchRequest) HasHiddenNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ProfilePatchRequest) HasAutoconnect() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ProfilePatchRequest) HasAutoconnectNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *ProfilePatchRequest) HasSecurity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Security != nil
}

func (x *ProfilePatchRequest) HasSecurityNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *ProfilePatchRequest) HasIpv4() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ipv4 != nil
}

func (x *ProfilePatchRequest) HasIpv4Null() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *ProfilePatchRequest) HasIpv6() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ipv6 != nil
}

func (x *ProfilePatchRequest) HasIpv6Null() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 16)
}

func (x *ProfilePatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ProfilePatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *ProfilePatchRequest) ClearNameNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_NameNull = false
}

func (x *ProfilePatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = nil
}

func (x *ProfilePatchRequest) ClearDescNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_DescNull = false
}

func (x *ProfilePatchRequest) ClearSsid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Ssid = nil
}

func (x *ProfilePatchRequest) ClearSsidNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_SsidNull = false
}

func (x *ProfilePatchRequest) ClearHidden() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Hidden = false
}

func (x *ProfilePatchRequest) ClearHiddenNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_HiddenNull = false
}

func (x *ProfilePatchRequest) ClearAutoconnect() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Autoconnect = false
}

func (x *ProfilePatchRequest) ClearAutoconnectNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_AutoconnectNull = false
}

func (x *ProfilePatchRequest) ClearSecurity() {
	x.xxx_hidden_Security = nil
}

func (x *ProfilePatchRequest) ClearSecurityNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_SecurityNull = false
}

func (x *ProfilePatchRequest) ClearIpv4() {
	x.xxx_hidden_Ipv4 = nil
}

func (x *ProfilePatchRequest) ClearIpv4Null() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_Ipv4Null = false
}

func (x *ProfilePatchRequest) ClearIpv6() {
	x.xxx_hidden_Ipv6 = nil
}

func (x *ProfilePatchRequest) ClearIpv6Null() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 16)
	x.xxx_hidden_Ipv6Null = false
}

type ProfilePatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref             *ProfileRef
	Name            *string
	NameNull        *bool
	Desc            *string
	DescNull        *bool
	Ssid            *string
	SsidNull        *bool
	Hidden          *bool
	HiddenNull      *bool
	Autoconnect     *bool
	AutoconnectNull *bool
	Security        *Security
	SecurityNull    *bool
	Ipv4            *IpConfig
	Ipv4Null        *bool
	Ipv6            *IpConfig
	Ipv6Null        *bool
}

func (b0 ProfilePatchRequest_builder) Build() *ProfilePatchRequest {
	m0 := &ProfilePatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 17)
		x.xxx_hidden_Name = b.Name
	}
	if b.NameNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 17)
		x.xxx_hidden_NameNull = *b.NameNull
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 17)
		x.xxx_hidden_Desc = b.Desc
	}
	if b.DescNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 17)
		x.xxx_hidden_DescNull = *b.DescNull
	}
	if b.Ssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 17)
		x.xxx_hidden_Ssid = b.Ssid
	}
	if b.SsidNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 17)
		x.xxx_hidden_SsidNull = *b.SsidNull
	}
	if b.Hidden != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 17)
		x.xxx_hidden_Hidden = *b.Hidden
	}
	if b.HiddenNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 17)
		x.xxx_hidden_HiddenNull = *b.HiddenNull
	}
	if b.Autoconnect != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 17)
		x.xxx_hidden_Autoconnect = *b.Autoconnect
	}
	if b.AutoconnectNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 17)
		x.xxx_hidden_AutoconnectNull = *b.AutoconnectNull
	}
	x.xxx_hidden_Security = b.Security
	if b.SecurityNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 17)
		x.xxx_hidden_SecurityNull = *b.SecurityNull
	}
	x.xxx_hidden_Ipv4 = b.Ipv4
	if b.Ipv4Null != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 17)
		x.xxx_hidden_Ipv4Null = *b.Ipv4Null
	}
	x.xxx_hidden_Ipv6 = b.Ipv6
	if b.Ipv6Null != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 16, 17)
		x.xxx_hidden_Ipv6Null = *b.Ipv6Null
	}
	return m0
}

type ProfileListRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileListRequest) Reset() {
	*x = ProfileListRequest{}
	mi := &file_wifi_profile_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileListRequest) ProtoMessage() {}

func (x *ProfileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_profile_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ProfileListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ProfileListRequest_builder) Build() *ProfileListRequest {
	m0 := &ProfileListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ProfileListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Profile            `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProfileListResponse) Reset() {
	*x = ProfileListResponse{}
	mi := &file_wifi_profile_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileListResponse) ProtoMessage() {}

func (x *ProfileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_profile_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileListResponse) GetItems() []*Profile {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ProfileListResponse) SetItems(v []*Profile) {
	x.xxx_hidden_Items = &v
}

type ProfileListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 프로파일 목록.
	Items []*Profile
}

func (b0 ProfileListResponse_builder) Build() *ProfileListResponse {
	m0 := &ProfileListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

var File_wifi_profile_svc_g_proto protoreflect.FileDescriptor

const file_wifi_profile_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x18wifi/profile_svc.g.proto\x12\x04wifi\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12wifi/profile.proto\x1a\x13wifi/security.proto\"\xcc\x02\n" +
	"\x11ProfileAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12\x12\n" +
	"\x04ssid\x18\a \x01(\tR\x04ssid\x12\x16\n" +
	"\x06hidden\x18\b \x01(\bR\x06hidden\x12 \n" +
	"\vautoconnect\x18\t \x01(\bR\vautoconnect\x12*\n" +
	"\bsecurity\x18\n" +
	" \x01(\v2\x0e.wifi.SecurityR\bsecurity\x12\"\n" +
	"\x04ipv4\x18\v \x01(\v2\x0e.wifi.IpConfigR\x04ipv4\x12\"\n" +
	"\x04ipv6\x18\f \x01(\v2\x0e.wifi.IpConfigR\x04ipv6\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\"%\n" +
	"\n" +
	"ProfileRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02idB\x05\n" +
	"\x03key\"\xfe\x01\n" +
	"\rProfileSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x12\n" +
	"\x04name\x18\x05 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\bR\x04desc\x12\x12\n" +
	"\x04ssid\x18\a \x01(\bR\x04ssid\x12\x16\n" +
	"\x06hidden\x18\b \x01(\bR\x06hidden\x12 \n" +
	"\vautoconnect\x18\t \x01(\bR\vautoconnect\x12\x1a\n" +
	"\bsecurity\x18\n" +
	" \x01(\bR\bsecurity\x12\x12\n" +
	"\x04ipv4\x18\v \x01(\bR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\f \x01(\bR\x04ipv6\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"d\n" +
	"\x11ProfileGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.wifi.ProfileRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.wifi.ProfileSelectR\x06select\"\xa5\x04\n" +
	"\x13ProfilePatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.wifi.ProfileRefR\x03ref\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x1b\n" +
	"\tname_null\x18\n" +
	" \x01(\bR\bnameNull\x12\x12\n" +
	"\x04desc\x18\v \x01(\tR\x04desc\x12\x1b\n" +
	"\tdesc_null\x18\f \x01(\bR\bdescNull\x12\x12\n" +
	"\x04ssid\x18\r \x01(\tR\x04ssid\x12\x1b\n" +
	"\tssid_null\x18\x0e \x01(\bR\bssidNull\x12\x16\n" +
	"\x06hidden\x18\x0f \x01(\bR\x06hidden\x12\x1f\n" +
	"\vhidden_null\x18\x10 \x01(\bR\n" +
	"hiddenNull\x12 \n" +
	"\vautoconnect\x18\x11 \x01(\bR\vautoconnect\x12)\n" +
	"\x10autoconnect_null\x18\x12 \x01(\bR\x0fautoconnectNull\x12*\n" +
	"\bsecurity\x18\x13 \x01(\v2\x0e.wifi.SecurityR\bsecurity\x12#\n" +
	"\rsecurity_null\x18\x14 \x01(\bR\fsecurityNull\x12\"\n" +
	"\x04ipv4\x18\x15 \x01(\v2\x0e.wifi.IpConfigR\x04ipv4\x12\x1b\n" +
	"\tipv4_null\x18\x16 \x01(\bR\bipv4Null\x12\"\n" +
	"\x04ipv6\x18\x17 \x01(\v2\x0e.wifi.IpConfigR\x04ipv6\x12\x1b\n" +
	"\tipv6_null\x18\x18 \x01(\bR\bipv6Null\"\x14\n" +
	"\x12ProfileListRequest\":\n" +
	"\x13ProfileListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.wifi.ProfileR\x05items2\x91\x02\n" +
	"\x0eProfileService\x12-\n" +
	"\x03Add\x12\x17.wifi.ProfileAddRequest\x1a\r.wifi.Profile\x12-\n" +
	"\x03Get\x12\x17.wifi.ProfileGetRequest\x1a\r.wifi.Profile\x121\n" +
	"\x05Patch\x12\x19.wifi.ProfilePatchRequest\x1a\r.wifi.Profile\x121\n" +
	"\x05Erase\x12\x10.wifi.ProfileRef\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x04List\x12\x18.wifi.ProfileListRequest\x1a\x19.wifi.ProfileListResponseB'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_profile_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wifi_profile_svc_g_proto_goTypes = []any{
	(*ProfileAddRequest)(nil),     // 0: wifi.ProfileAddRequest
	(*ProfileRef)(nil),            // 1: wifi.ProfileRef
	(*ProfileSelect)(nil),         // 2: wifi.ProfileSelect
	(*ProfileGetRequest)(nil),     // 3: wifi.ProfileGetRequest
	(*ProfilePatchRequest)(nil),   // 4: wifi.ProfilePatchRequest
	(*ProfileListRequest)(nil),    // 5: wifi.ProfileListRequest
	(*ProfileListResponse)(nil),   // 6: wifi.ProfileListResponse
	(*Security)(nil),              // 7: wifi.Security
	(*IpConfig)(nil),              // 8: wifi.IpConfig
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*Profile)(nil),               // 10: wifi.Profile
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_wifi_profile_svc_g_proto_depIdxs = []int32{
	7,  // 0: wifi.ProfileAddRequest.security:type_name -> wifi.Security
	8,  // 1: wifi.ProfileAddRequest.ipv4:type_name -> wifi.IpConfig
	8,  // 2: wifi.ProfileAddRequest.ipv6:type_name -> wifi.IpConfig
	9,  // 3: wifi.ProfileAddRequest.date_created:type_name -> google.protobuf.Timestamp
	1,  // 4: wifi.ProfileGetRequest.ref:type_name -> wifi.ProfileRef
	2,  // 5: wifi.ProfileGetRequest.select:type_name -> wifi.ProfileSelect
	1,  // 6: wifi.ProfilePatchRequest.ref:type_name -> wifi.ProfileRef
	7,  // 7: wifi.ProfilePatchRequest.security:type_name -> wifi.Security
	8,  // 8: wifi.ProfilePatchRequest.ipv4:type_name -> wifi.IpConfig
	8,  // 9: wifi.ProfilePatchRequest.ipv6:type_name -> wifi.IpConfig
	10, // 10: wifi.ProfileListResponse.items:type_name -> wifi.Profile
	0,  // 11: wifi.ProfileService.Add:input_type -> wifi.ProfileAddRequest
	3,  // 12: wifi.ProfileService.Get:input_type -> wifi.ProfileGetRequest
	4,  // 13: wifi.ProfileService.Patch:input_type -> wifi.ProfilePatchRequest
	1,  // 14: wifi.ProfileService.Erase:input_type -> wifi.ProfileRef
	5,  // 15: wifi.ProfileService.List:input_type -> wifi.ProfileListRequest
	10, // 16: wifi.ProfileService.Add:output_type -> wifi.Profile
	10, // 17: wifi.ProfileService.Get:output_type -> wifi.Profile
	10, // 18: wifi.ProfileService.Patch:output_type -> wifi.Profile
	11, // 19: wifi.ProfileService.Erase:output_type -> google.protobuf.Empty
	6,  // 20: wifi.ProfileService.List:output_type -> wifi.ProfileListResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_wifi_profile_svc_g_proto_init() }
func file_wifi_profile_svc_g_proto_init() {
	if File_wifi_profile_svc_g_proto != nil {
		return
	}
	file_wifi_profile_proto_init()
	file_wifi_security_proto_init()
	file_wifi_profile_svc_g_proto_msgTypes[1].OneofWrappers = []any{
		(*profileRef_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_profile_svc_g_proto_rawDesc), len(file_wifi_profile_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wifi_profile_svc_g_proto_goTypes,
		DependencyIndexes: file_wifi_profile_svc_g_proto_depIdxs,
		MessageInfos:      file_wifi_profile_svc_g_proto_msgTypes,
	}.Build()
	File_wifi_profile_svc_g_proto = out.File
	file_wifi_profile_svc_g_proto_goTypes = nil
	file_wifi_profile_svc_g_proto_depIdxs = nil
}
