// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/profile.proto

package wifi

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 자동/수동 할당을 선택한다.
type IpConfig_Method int32

const (
	IpConfig_METHOD_UNSPECIFIED IpConfig_Method = 0
	// 자동: IPv4는 DHCP, IPv6는 SLAAC/DHCPv6로 할당받는다.
	IpConfig_METHOD_AUTO IpConfig_Method = 1
	// 수동: 아래 필드들로 정적 설정한다.
	IpConfig_METHOD_MANUAL IpConfig_Method = 2
	// 이 주소 체계를 구성하지 않는다.
	IpConfig_METHOD_DISABLED IpConfig_Method = 3
)

// Enum value maps for IpConfig_Method.
var (
	IpConfig_Method_name = map[int32]string{
		0: "METHOD_UNSPECIFIED",
		1: "METHOD_AUTO",
		2: "METHOD_MANUAL",
		3: "METHOD_DISABLED",
	}
	IpConfig_Method_value = map[string]int32{
		"METHOD_UNSPECIFIED": 0,
		"METHOD_AUTO":        1,
		"METHOD_MANUAL":      2,
		"METHOD_DISABLED":    3,
	}
)

func (x IpConfig_Method) Enum() *IpConfig_Method {
	p := new(IpConfig_Method)
	*p = x
	return p
}

func (x IpConfig_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpConfig_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_profile_proto_enumTypes[0].Descriptor()
}

func (IpConfig_Method) Type() protoreflect.EnumType {
	return &file_wifi_profile_proto_enumTypes[0]
}

func (x IpConfig_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// IpConfig는 한 주소 체계(IPv4 또는 IPv6)의 주소 할당 방식을 기술한다.
// Profile에 내장되는(JSON으로 저장되는) 값 객체다.
type IpConfig struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Method      IpConfig_Method        `protobuf:"varint,1,opt,name=method,enum=wifi.IpConfig_Method"`
	xxx_hidden_Addresses   []string               `protobuf:"bytes,2,rep,name=addresses"`
	xxx_hidden_Gateway     *string                `protobuf:"bytes,3,opt,name=gateway"`
	xxx_hidden_Dns         []string               `protobuf:"bytes,4,rep,name=dns"`
	xxx_hidden_DnsSearch   []string               `protobuf:"bytes,5,rep,name=dns_search,json=dnsSearch"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IpConfig) Reset() {
	*x = IpConfig{}
	mi := &file_wifi_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpConfig) ProtoMessage() {}

func (x *IpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IpConfig) GetMethod() IpConfig_Method {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Method
		}
	}
	return IpConfig_METHOD_UNSPECIFIED
}

func (x *IpConfig) GetAddresses() []string {
	if x != nil {
		return x.xxx_hidden_Addresses
	}
	return nil
}

func (x *IpConfig) GetGateway() string {
	if x != nil {
		if x.xxx_hidden_Gateway != nil {
			return *x.xxx_hidden_Gateway
		}
		return ""
	}
	return ""
}

func (x *IpConfig) GetDns() []string {
	if x != nil {
		return x.xxx_hidden_Dns
	}
	return nil
}

func (x *IpConfig) GetDnsSearch() []string {
	if x != nil {
		return x.xxx_hidden_DnsSearch
	}
	return nil
}

func (x *IpConfig) SetMethod(v IpConfig_Method) {
	x.xxx_hidden_Method = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *IpConfig) SetAddresses(v []string) {
	x.xxx_hidden_Addresses = v
}

func (x *IpConfig) SetGateway(v string) {
	x.xxx_hidden_Gateway = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *IpConfig) SetDns(v []string) {
	x.xxx_hidden_Dns = v
}

func (x *IpConfig) SetDnsSearch(v []string) {
	x.xxx_hidden_DnsSearch = v
}

func (x *IpConfig) HasMethod() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *IpConfig) HasGateway() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *IpConfig) ClearMethod() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Method = IpConfig_METHOD_UNSPECIFIED
}

func (x *IpConfig) ClearGateway() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Gateway = nil
}

type IpConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Method *IpConfig_Method
	// CIDR 표기의 주소 목록. 예: "192.168.1.10/24".
	Addresses []string
	// 기본 게이트웨이. 예: "192.168.1.1".
	Gateway *string
	// DNS 서버 주소 목록. 예: "1.1.1.1".
	Dns []string
	// DNS 검색 도메인 목록.
	DnsSearch []string
}

func (b0 IpConfig_builder) Build() *IpConfig {
	m0 := &IpConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Method != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Method = *b.Method
	}
	x.xxx_hidden_Addresses = b.Addresses
	if b.Gateway != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Gateway = b.Gateway
	}
	x.xxx_hidden_Dns = b.Dns
	x.xxx_hidden_DnsSearch = b.DnsSearch
	return m0
}

// Profile은 과거에 연결했던(또는 앞으로 연결할) 설정을 저장하는 기록이다.
//
// 대상 네트워크(SSID), 인증 방법(Security), IP/DNS 설정을 담는다.
// 실제 연결은 이 Profile을 특정 Interface에 적용하여 Connection으로
// 활성화함으로써 이루어진다. 사용자가 직접 만들고 관리하는 대상이므로
// 전체 CRUD를 제공한다.
type Profile struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        *string                `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Ssid        *string                `protobuf:"bytes,7,opt,name=ssid"`
	xxx_hidden_Hidden      bool                   `protobuf:"varint,8,opt,name=hidden"`
	xxx_hidden_Autoconnect bool                   `protobuf:"varint,9,opt,name=autoconnect"`
	xxx_hidden_Security    *Security              `protobuf:"bytes,10,opt,name=security"`
	xxx_hidden_Ipv4        *IpConfig              `protobuf:"bytes,11,opt,name=ipv4"`
	xxx_hidden_Ipv6        *IpConfig              `protobuf:"bytes,12,opt,name=ipv6"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_wifi_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Profile) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Profile) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Profile) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *Profile) GetSsid() string {
	if x != nil {
		if x.xxx_hidden_Ssid != nil {
			return *x.xxx_hidden_Ssid
		}
		return ""
	}
	return ""
}

func (x *Profile) GetHidden() bool {
	if x != nil {
		return x.xxx_hidden_Hidden
	}
	return false
}

func (x *Profile) GetAutoconnect() bool {
	if x != nil {
		return x.xxx_hidden_Autoconnect
	}
	return false
}

func (x *Profile) GetSecurity() *Security {
	if x != nil {
		return x.xxx_hidden_Security
	}
	return nil
}

func (x *Profile) GetIpv4() *IpConfig {
	if x != nil {
		return x.xxx_hidden_Ipv4
	}
	return nil
}

func (x *Profile) GetIpv6() *IpConfig {
	if x != nil {
		return x.xxx_hidden_Ipv6
	}
	return nil
}

func (x *Profile) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Profile) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *Profile) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *Profile) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *Profile) SetSsid(v string) {
	x.xxx_hidden_Ssid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *Profile) SetHidden(v bool) {
	x.xxx_hidden_Hidden = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *Profile) SetAutoconnect(v bool) {
	x.xxx_hidden_Autoconnect = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *Profile) SetSecurity(v *Security) {
	x.xxx_hidden_Security = v
}

func (x *Profile) SetIpv4(v *IpConfig) {
	x.xxx_hidden_Ipv4 = v
}

func (x *Profile) SetIpv6(v *IpConfig) {
	x.xxx_hidden_Ipv6 = v
}

func (x *Profile) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Profile) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Profile) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Profile) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Profile) HasSsid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Profile) HasHidden() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Profile) HasAutoconnect() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Profile) HasSecurity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Security != nil
}

func (x *Profile) HasIpv4() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ipv4 != nil
}

func (x *Profile) HasIpv6() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ipv6 != nil
}

func (x *Profile) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Profile) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Profile) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Profile) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Desc = nil
}

func (x *Profile) ClearSsid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Ssid = nil
}

func (x *Profile) ClearHidden() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Hidden = false
}

func (x *Profile) ClearAutoconnect() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Autoconnect = false
}

func (x *Profile) ClearSecurity() {
	x.xxx_hidden_Security = nil
}

func (x *Profile) ClearIpv4() {
	x.xxx_hidden_Ipv4 = nil
}

func (x *Profile) ClearIpv6() {
	x.xxx_hidden_Ipv6 = nil
}

func (x *Profile) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Profile_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 프로파일 식별자(자동 생성 UUID).
	Id []byte
	// 사람이 읽기 위한 이름. 예: "집 와이파이".
	Name *string
	// 설명.
	Desc *string
	// 연결 대상 네트워크 이름(SSID). 필수 값이다.
	Ssid *string
	// SSID가 숨겨진(브로드캐스트되지 않는) 네트워크인지 여부.
	// 숨김 네트워크는 스캔에 보이지 않으므로 SSID를 직접 지정해 연결한다.
	Hidden *bool
	// 네트워크가 범위 안에 들어오면 자동으로 연결할지 여부.
	Autoconnect *bool
	// 이 네트워크에 인증하는 방법. 개방형이면 Security.open을 사용한다.
	Security *Security
	// IPv4 주소 설정. 지정하지 않으면 자동(DHCP)으로 동작한다.
	Ipv4 *IpConfig
	// IPv6 주소 설정. 지정하지 않으면 자동으로 동작한다.
	Ipv6 *IpConfig
	// 프로파일이 처음 생성된 시각.
	DateCreated *timestamppb.Timestamp
}

func (b0 Profile_builder) Build() *Profile {
	m0 := &Profile{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_Desc = b.Desc
	}
	if b.Ssid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_Ssid = b.Ssid
	}
	if b.Hidden != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_Hidden = *b.Hidden
	}
	if b.Autoconnect != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_Autoconnect = *b.Autoconnect
	}
	x.xxx_hidden_Security = b.Security
	x.xxx_hidden_Ipv4 = b.Ipv4
	x.xxx_hidden_Ipv6 = b.Ipv6
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_wifi_profile_proto protoreflect.FileDescriptor

const file_wifi_profile_proto_rawDesc = "" +
	"\n" +
	"\x12wifi/profile.proto\x12\x04wifi\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\x13wifi/security.proto\"\xfd\x01\n" +
	"\bIpConfig\x12-\n" +
	"\x06method\x18\x01 \x01(\x0e2\x15.wifi.IpConfig.MethodR\x06method\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\x12\x10\n" +
	"\x03dns\x18\x04 \x03(\tR\x03dns\x12\x1d\n" +
	"\n" +
	"dns_search\x18\x05 \x03(\tR\tdnsSearch\"Y\n" +
	"\x06Method\x12\x16\n" +
	"\x12METHOD_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMETHOD_AUTO\x10\x01\x12\x11\n" +
	"\rMETHOD_MANUAL\x10\x02\x12\x13\n" +
	"\x0fMETHOD_DISABLED\x10\x03\"\x98\x03\n" +
	"\aProfile\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12\x1b\n" +
	"\x04name\x18\x05 \x01(\tB\a\xea\x82\x16\x03\x82\x01\x00R\x04name\x12\x1b\n" +
	"\x04desc\x18\x06 \x01(\tB\a\xea\x82\x16\x03\x82\x01\x00R\x04desc\x12\x12\n" +
	"\x04ssid\x18\a \x01(\tR\x04ssid\x12\x1f\n" +
	"\x06hidden\x18\b \x01(\bB\a\xea\x82\x16\x03\x82\x01\x00R\x06hidden\x12)\n" +
	"\vautoconnect\x18\t \x01(\bB\a\xea\x82\x16\x03\x82\x01\x00R\vautoconnect\x12*\n" +
	"\bsecurity\x18\n" +
	" \x01(\v2\x0e.wifi.SecurityR\bsecurity\x12*\n" +
	"\x04ipv4\x18\v \x01(\v2\x0e.wifi.IpConfigB\x06\xea\x82\x16\x028\x01R\x04ipv4\x12*\n" +
	"\x04ipv6\x18\f \x01(\v2\x0e.wifi.IpConfigB\x06\xea\x82\x16\x028\x01R\x04ipv6\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:\b\xca\xfc\x15\x04\x12\x02\x10\x01B'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wifi_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wifi_profile_proto_goTypes = []any{
	(IpConfig_Method)(0),          // 0: wifi.IpConfig.Method
	(*IpConfig)(nil),              // 1: wifi.IpConfig
	(*Profile)(nil),               // 2: wifi.Profile
	(*Security)(nil),              // 3: wifi.Security
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_wifi_profile_proto_depIdxs = []int32{
	0, // 0: wifi.IpConfig.method:type_name -> wifi.IpConfig.Method
	3, // 1: wifi.Profile.security:type_name -> wifi.Security
	1, // 2: wifi.Profile.ipv4:type_name -> wifi.IpConfig
	1, // 3: wifi.Profile.ipv6:type_name -> wifi.IpConfig
	4, // 4: wifi.Profile.date_created:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_wifi_profile_proto_init() }
func file_wifi_profile_proto_init() {
	if File_wifi_profile_proto != nil {
		return
	}
	file_wifi_security_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_profile_proto_rawDesc), len(file_wifi_profile_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_profile_proto_goTypes,
		DependencyIndexes: file_wifi_profile_proto_depIdxs,
		EnumInfos:         file_wifi_profile_proto_enumTypes,
		MessageInfos:      file_wifi_profile_proto_msgTypes,
	}.Build()
	File_wifi_profile_proto = out.File
	file_wifi_profile_proto_goTypes = nil
	file_wifi_profile_proto_depIdxs = nil
}
