// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi/security.proto

package wifi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Security describes how to authenticate to a network.
//
// For now only a password (PSK) is supported, but since AP connections have
// other methods too, the credential is defined as a oneof so it can be extended
// in the future (802.1X/EAP, WPS, etc.). New methods can be added as entries to
// the oneof without breaking existing profiles.
//
// This message is not an ORM entity but a value object embedded in a Profile
// (stored as JSON). The enum of authentication methods an AP advertises is kept
// alongside AccessPoint (see KeyManagement in access_point.proto).
type Security struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Credential isSecurity_Credential  `protobuf_oneof:"credential"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_wifi_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Security) GetOpen() *Security_Open {
	if x != nil {
		if x, ok := x.xxx_hidden_Credential.(*security_Open_); ok {
			return x.Open
		}
	}
	return nil
}

func (x *Security) GetPsk() *Security_Psk {
	if x != nil {
		if x, ok := x.xxx_hidden_Credential.(*security_Psk_); ok {
			return x.Psk
		}
	}
	return nil
}

func (x *Security) GetEnterprise() *Security_Enterprise {
	if x != nil {
		if x, ok := x.xxx_hidden_Credential.(*security_Enterprise_); ok {
			return x.Enterprise
		}
	}
	return nil
}

func (x *Security) SetOpen(v *Security_Open) {
	if v == nil {
		x.xxx_hidden_Credential = nil
		return
	}
	x.xxx_hidden_Credential = &security_Open_{v}
}

func (x *Security) SetPsk(v *Security_Psk) {
	if v == nil {
		x.xxx_hidden_Credential = nil
		return
	}
	x.xxx_hidden_Credential = &security_Psk_{v}
}

func (x *Security) SetEnterprise(v *Security_Enterprise) {
	if v == nil {
		x.xxx_hidden_Credential = nil
		return
	}
	x.xxx_hidden_Credential = &security_Enterprise_{v}
}

func (x *Security) HasCredential() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Credential != nil
}

func (x *Security) HasOpen() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Credential.(*security_Open_)
	return ok
}

func (x *Security) HasPsk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Credential.(*security_Psk_)
	return ok
}

func (x *Security) HasEnterprise() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Credential.(*security_Enterprise_)
	return ok
}

func (x *Security) ClearCredential() {
	x.xxx_hidden_Credential = nil
}

func (x *Security) ClearOpen() {
	if _, ok := x.xxx_hidden_Credential.(*security_Open_); ok {
		x.xxx_hidden_Credential = nil
	}
}

func (x *Security) ClearPsk() {
	if _, ok := x.xxx_hidden_Credential.(*security_Psk_); ok {
		x.xxx_hidden_Credential = nil
	}
}

func (x *Security) ClearEnterprise() {
	if _, ok := x.xxx_hidden_Credential.(*security_Enterprise_); ok {
		x.xxx_hidden_Credential = nil
	}
}

const Security_Credential_not_set_case case_Security_Credential = 0
const Security_Open_case case_Security_Credential = 1
const Security_Psk_case case_Security_Credential = 2
const Security_Enterprise_case case_Security_Credential = 3

func (x *Security) WhichCredential() case_Security_Credential {
	if x == nil {
		return Security_Credential_not_set_case
	}
	switch x.xxx_hidden_Credential.(type) {
	case *security_Open_:
		return Security_Open_case
	case *security_Psk_:
		return Security_Psk_case
	case *security_Enterprise_:
		return Security_Enterprise_case
	default:
		return Security_Credential_not_set_case
	}
}

type Security_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The credential to use. Exactly one is set.

	// Fields of oneof xxx_hidden_Credential:
	// For cases that need no credential, such as open / OWE.
	Open *Security_Open
	// Pre-shared key (password). Covers both WPA-PSK and WPA3-SAE.
	Psk *Security_Psk
	// 802.1X/EAP enterprise credential. A placeholder for future implementation.
	Enterprise *Security_Enterprise
	// -- end of xxx_hidden_Credential
}

func (b0 Security_builder) Build() *Security {
	m0 := &Security{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Open != nil {
		x.xxx_hidden_Credential = &security_Open_{b.Open}
	}
	if b.Psk != nil {
		x.xxx_hidden_Credential = &security_Psk_{b.Psk}
	}
	if b.Enterprise != nil {
		x.xxx_hidden_Credential = &security_Enterprise_{b.Enterprise}
	}
	return m0
}

type case_Security_Credential protoreflect.FieldNumber

func (x case_Security_Credential) String() string {
	md := file_wifi_security_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSecurity_Credential interface {
	isSecurity_Credential()
}

type security_Open_ struct {
	// For cases that need no credential, such as open / OWE.
	Open *Security_Open `protobuf:"bytes,1,opt,name=open,oneof"`
}

type security_Psk_ struct {
	// Pre-shared key (password). Covers both WPA-PSK and WPA3-SAE.
	Psk *Security_Psk `protobuf:"bytes,2,opt,name=psk,oneof"`
}

type security_Enterprise_ struct {
	// 802.1X/EAP enterprise credential. A placeholder for future implementation.
	Enterprise *Security_Enterprise `protobuf:"bytes,3,opt,name=enterprise,oneof"`
}

func (*security_Open_) isSecurity_Credential() {}

func (*security_Psk_) isSecurity_Credential() {}

func (*security_Enterprise_) isSecurity_Credential() {}

// Represents a network that needs no credential.
type Security_Open struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_Open) Reset() {
	*x = Security_Open{}
	mi := &file_wifi_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_Open) ProtoMessage() {}

func (x *Security_Open) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Security_Open_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Security_Open_builder) Build() *Security_Open {
	m0 := &Security_Open{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Corresponds to the "password" the user enters.
type Security_Psk struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Passphrase  *string                `protobuf:"bytes,1,opt,name=passphrase"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Security_Psk) Reset() {
	*x = Security_Psk{}
	mi := &file_wifi_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_Psk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_Psk) ProtoMessage() {}

func (x *Security_Psk) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Security_Psk) GetPassphrase() string {
	if x != nil {
		if x.xxx_hidden_Passphrase != nil {
			return *x.xxx_hidden_Passphrase
		}
		return ""
	}
	return ""
}

func (x *Security_Psk) SetPassphrase(v string) {
	x.xxx_hidden_Passphrase = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *Security_Psk) HasPassphrase() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Security_Psk) ClearPassphrase() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Passphrase = nil
}

type Security_Psk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Passphrase (pre-shared key).
	Passphrase *string
}

func (b0 Security_Psk_builder) Build() *Security_Psk {
	m0 := &Security_Psk{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Passphrase != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Passphrase = b.Passphrase
	}
	return m0
}

// Placeholder for 802.1X/EAP-based authentication.
// The EAP method, identity, certificates, etc. are added at actual implementation time.
type Security_Enterprise struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_Enterprise) Reset() {
	*x = Security_Enterprise{}
	mi := &file_wifi_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_Enterprise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_Enterprise) ProtoMessage() {}

func (x *Security_Enterprise) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Security_Enterprise_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Security_Enterprise_builder) Build() *Security_Enterprise {
	m0 := &Security_Enterprise{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_wifi_security_proto protoreflect.FileDescriptor

const file_wifi_security_proto_rawDesc = "" +
	"\n" +
	"\x13wifi/security.proto\x12\x04wifi\"\xe5\x01\n" +
	"\bSecurity\x12)\n" +
	"\x04open\x18\x01 \x01(\v2\x13.wifi.Security.OpenH\x00R\x04open\x12&\n" +
	"\x03psk\x18\x02 \x01(\v2\x12.wifi.Security.PskH\x00R\x03psk\x12;\n" +
	"\n" +
	"enterprise\x18\x03 \x01(\v2\x19.wifi.Security.EnterpriseH\x00R\n" +
	"enterprise\x1a\x06\n" +
	"\x04Open\x1a%\n" +
	"\x03Psk\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x01 \x01(\tR\n" +
	"passphrase\x1a\f\n" +
	"\n" +
	"EnterpriseB\f\n" +
	"\n" +
	"credentialB'Z%github.com/lesomnus/wfm/internal/wifib\beditionsp\xe8\a"

var file_wifi_security_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wifi_security_proto_goTypes = []any{
	(*Security)(nil),            // 0: wifi.Security
	(*Security_Open)(nil),       // 1: wifi.Security.Open
	(*Security_Psk)(nil),        // 2: wifi.Security.Psk
	(*Security_Enterprise)(nil), // 3: wifi.Security.Enterprise
}
var file_wifi_security_proto_depIdxs = []int32{
	1, // 0: wifi.Security.open:type_name -> wifi.Security.Open
	2, // 1: wifi.Security.psk:type_name -> wifi.Security.Psk
	3, // 2: wifi.Security.enterprise:type_name -> wifi.Security.Enterprise
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wifi_security_proto_init() }
func file_wifi_security_proto_init() {
	if File_wifi_security_proto != nil {
		return
	}
	file_wifi_security_proto_msgTypes[0].OneofWrappers = []any{
		(*security_Open_)(nil),
		(*security_Psk_)(nil),
		(*security_Enterprise_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_security_proto_rawDesc), len(file_wifi_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_security_proto_goTypes,
		DependencyIndexes: file_wifi_security_proto_depIdxs,
		MessageInfos:      file_wifi_security_proto_msgTypes,
	}.Build()
	File_wifi_security_proto = out.File
	file_wifi_security_proto_goTypes = nil
	file_wifi_security_proto_depIdxs = nil
}
