edition = "2023";
package wifi;

import "google/protobuf/empty.proto";
import "wifi/access_point.proto";
import "wifi/interface_svc.g.proto";

option go_package = "github.com/lesomnus/wfm/internal/wifi";

service AccessPointService {
  // Add creates a new AccessPoint
  rpc Add(AccessPointAddRequest) returns (AccessPoint);
  // Get retrieves a AccessPoint
  rpc Get(AccessPointGetRequest) returns (AccessPoint);
  // Patch updates an existing AccessPoint
  rpc Patch(AccessPointPatchRequest) returns (AccessPoint);
  // Erase deletes a AccessPoint
  rpc Erase(AccessPointRef) returns (google.protobuf.Empty);
  // Scan discovers nearby APs using the given interface and returns the list.
  rpc Scan(AccessPointScanRequest) returns (AccessPointScanResponse);
}

message AccessPointAddRequest {
  string id = 1;
  string ssid = 2;
  string bssid = 3;
  int32 signal = 4;
  uint32 frequency = 5;
  repeated KeyManagement key_management = 6;
}

message AccessPointGetRequest {
  AccessPointRef ref = 1;
  AccessPointSelect select = 2;
}

message AccessPointRef {
  oneof key {
    string id = 1;
  }
}

message AccessPointSelect {
  bool all = 1;
  bool ssid = 2;
  bool bssid = 3;
  bool signal = 4;
  bool frequency = 5;
  bool key_management = 6;
}

message AccessPointPatchRequest {
  AccessPointRef ref = 1;
  string ssid = 3;
  bool ssid_null = 4;
  string bssid = 5;
  bool bssid_null = 6;
  int32 signal = 7;
  bool signal_null = 8;
  uint32 frequency = 9;
  bool frequency_null = 10;
  repeated KeyManagement key_management = 11;
}

message AccessPointScanRequest {
  // The wireless interface to scan with. Must be specified since a node may have
  // multiple interfaces.
  InterfaceRef interface = 1;
}

message AccessPointScanResponse {
  // List of discovered APs.
  repeated AccessPoint items = 1;
}
