edition = "2023";
package wifi;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "wifi/profile.proto";
import "wifi/security.proto";

option go_package = "github.com/lesomnus/wfm/internal/wifi";

service ProfileService {
  // Add creates a new Profile
  rpc Add(ProfileAddRequest) returns (Profile);
  // Get retrieves a Profile
  rpc Get(ProfileGetRequest) returns (Profile);
  // Patch updates an existing Profile
  rpc Patch(ProfilePatchRequest) returns (Profile);
  // Erase deletes a Profile
  rpc Erase(ProfileRef) returns (google.protobuf.Empty);
  // List enumerates all stored profiles.
  rpc List(ProfileListRequest) returns (ProfileListResponse);
}

message ProfileAddRequest {
  bytes id = 1;
  string name = 5;
  string desc = 6;
  string ssid = 7;
  bool hidden = 8;
  bool autoconnect = 9;
  Security security = 10;
  IpConfig ipv4 = 11;
  IpConfig ipv6 = 12;
  google.protobuf.Timestamp date_created = 15;
}

message ProfileGetRequest {
  ProfileRef ref = 1;
  ProfileSelect select = 2;
}

message ProfileRef {
  oneof key {
    bytes id = 1;
  }
}

message ProfileSelect {
  bool all = 1;
  bool name = 5;
  bool desc = 6;
  bool ssid = 7;
  bool hidden = 8;
  bool autoconnect = 9;
  bool security = 10;
  bool ipv4 = 11;
  bool ipv6 = 12;
  bool date_created = 15;
}

message ProfilePatchRequest {
  ProfileRef ref = 1;
  string name = 9;
  bool name_null = 10;
  string desc = 11;
  bool desc_null = 12;
  string ssid = 13;
  bool ssid_null = 14;
  bool hidden = 15;
  bool hidden_null = 16;
  bool autoconnect = 17;
  bool autoconnect_null = 18;
  Security security = 19;
  bool security_null = 20;
  IpConfig ipv4 = 21;
  bool ipv4_null = 22;
  IpConfig ipv6 = 23;
  bool ipv6_null = 24;
}

message ProfileListRequest {}

message ProfileListResponse {
  // List of profiles.
  repeated Profile items = 1;
}
